/**
 * Castor Theme
 *
 * Generated by /pipeline.stitch-design
 * Stitch project: Castor Plumber Website (id: 6140073857739228197)
 * Trade type: plumber
 *
 * Palette: Trade Navy (#1a3a6b) + Fresh Sage (#3a7d44) + Clean White
 * Fonts: Newsreader (headline) + Work Sans (body)
 *
 * Sites using Castor: (none yet)
 */
import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const castorRegistry: ComponentRegistry = {
  theme: "castor",
  heroVariant: "image-overlay",
  headerVariant: "light",
  cardVariant: "standard",
  sectionVariant: "banded",
};

export const castorDefaultConfig: DeepPartialThemeConfig = {
  colors: {
    brand: {
      primary: "#1a3a6b", // Trade Navy
      primaryHover: "#142d54", // Darkened ~12%
      secondary: "#1a3a6b", // Same navy for secondary surfaces
      accent: "#3a7d44", // Fresh Sage — CTA buttons, highlights
      onPrimary: "#ffffff",
    },
    surface: {
      background: "#ffffff", // Clean White canvas
      foreground: "#1c1c1e", // Off-Black Ink
      card: "#ffffff",
      cardBorder: "#e2e8f0", // Whisper Border
      muted: "#f0f4f8", // Mist Grey
    },
    semantic: {
      success: "#10b981",
      warning: "#f59e0b",
      error: "#ef4444",
      info: "#3b82f6",
    },
    overlay: {
      dark: "rgba(0,0,0,0.8)",
      light: "rgba(255,255,255,0.8)",
      primary: "rgba(26,58,107,0.75)", // Slate Overlay — navy-tinted hero scrim
    },
  },
};

registerTheme({ name: "castor", label: "Castor", config: castorDefaultConfig });
