import type { DeepPartialThemeConfig } from '@platform/theme-system';
import { rigelRegistry, rigelDefaultConfig } from '@platform/themes/rigel';

/**
 * Test site theme configuration
 * Generated by /pipeline.ingest
 */
export const themeConfig: DeepPartialThemeConfig = {
  componentRegistry: rigelRegistry,
  ...rigelDefaultConfig,
  colors: {
    ...rigelDefaultConfig.colors,
    surface: {
      ...rigelDefaultConfig.colors?.surface,
      inverse: '#292661',
    },
  },
};
