import type { DeepPartialThemeConfig } from '@platform/theme-system';
import { lyraRegistry, lyraDefaultConfig } from '@platform/themes/lyra';

/**
 * Test site theme configuration
 * Generated by /pipeline.ingest
 */
export const themeConfig: DeepPartialThemeConfig = {
  componentRegistry: lyraRegistry,
  ...lyraDefaultConfig,
};
