/**
 * Lyra Theme
 *
 * Generated by Stitch design exploration (manual extraction, not the full
 * /pipeline.stitch-design run — see output/ingestion/lyra-stitch/).
 * Stitch project: DCH Automotive Website (id: 6609563365548103094)
 * Trade type: vehicle security, fleet electrics and ECU remapping installer
 *
 * Dark-first identity — not light-with-a-dark-section like orion/vega.
 * Near-black background (#0C0B09), off-white text, a single confident
 * orange accent (#F2730D) used sparingly for CTAs/icons/highlights only.
 * See globals.css header comment for the `surface.inverse` architectural
 * note (Lyra's "inverse" is the LIGHT end of the palette, the opposite of
 * every other theme so far).
 *
 * Font substitution note: Oswald was requested from Stitch but it resolved
 * headlines to Public Sans at font-weight 900 with tight tracking — kept
 * as-generated (bold/condensed-reading, trade-credible) rather than forced
 * back to the original request. See output/ingestion/lyra-stitch/design-system/tokens.json.
 *
 * Contrast note: the generated screens use white button text on the orange
 * background (not black) — kept as observed/approved rather than
 * substituted for a higher-contrast pairing. Worth a WCAG check
 * (`pnpm --filter @platform/theme-system validate`) before shipping.
 *
 * Sites using Lyra: (none yet — design-direction review only, no test site built)
 */
import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const lyraRegistry: ComponentRegistry = {
  theme: "lyra",
  heroVariant: "image-overlay",
  headerVariant: "dark",
  cardVariant: "standard",
  sectionVariant: "standard",
};

export const lyraDefaultConfig: DeepPartialThemeConfig = {
  colors: {
    brand: {
      primary: "#F2730D",
      primaryHover: "#D9640A",
      secondary: "#1C1B19",
      accent: "#FF8B3D",
      onPrimary: "#FFFFFF",
      light: "#FF8B3D",
      dark: "#0C0B09",
    },
    surface: {
      background: "#0C0B09",
      foreground: "#F5F5F5",
      secondaryForeground: "#C9C4BA",
      tertiaryForeground: "#8B857A",
      muted: "#1C1B19",
      mutedForeground: "#A8A29C",
      card: "#1C1B19",
      cardBorder: "rgba(255,255,255,0.1)",
      subtle: "#141311",
      subtleBorder: "rgba(255,255,255,0.06)",
      inverse: "#F5F5F5",
      inverseMutedForeground: "#55524C",
    },
    semantic: { success: "#10b981", warning: "#f59e0b", error: "#ef4444", info: "#3b82f6" },
    overlay: {
      dark: "rgba(12,11,9,0.8)",
      light: "rgba(245,245,245,0.8)",
      primary: "rgba(242,115,13,0.8)",
    },
  },
};

registerTheme({ name: "lyra", label: "Lyra", config: lyraDefaultConfig });
