/**
 * Rigel Theme — Component Manifest
 *
 * Auto-generated from reference analysis.
 * Maps blueprint metadata for tooling and showcase integration.
 */

import type { ComponentCategory } from '../../theme-system/src/types';

export interface ThemeComponentEntry {
  slug: string;
  name: string;
  category: ComponentCategory;
  exportName: string;
  importPath: string;
}

export const manifest: ThemeComponentEntry[] = [
  {
    slug: "navigation-top-bar",
    name: "TopNavigation",
    category: "Navigation",
    exportName: "TopNavigation",
    importPath: "./components/top-navigation",
  },
  {
    slug: "cta-newsletter-signup",
    name: "NewsletterSignupCTA",
    category: "CTA",
    exportName: "NewsletterSignupCTA",
    importPath: "./components/newsletter-signup-cta",
  },
  {
    slug: "footer-multi-column-links",
    name: "SiteFooter",
    category: "Footer",
    exportName: "SiteFooter",
    importPath: "./components/site-footer",
  },
  {
    slug: "hero-full-bleed-text",
    name: "HeroHeadline",
    category: "Hero",
    exportName: "HeroHeadline",
    importPath: "./components/hero-headline",
  },
  {
    slug: "hero-event-details-split",
    name: "EventDetailsBanner",
    category: "Hero",
    exportName: "EventDetailsBanner",
    importPath: "./components/event-details-banner",
  },
  {
    slug: "hero-page-title-banner",
    name: "PageTitleBanner",
    category: "Hero",
    exportName: "PageTitleBanner",
    importPath: "./components/page-title-banner",
  },
  {
    slug: "cta-call-for-speakers-yellow",
    name: "CallForSpeakersCTA",
    category: "CTA",
    exportName: "CallForSpeakersCTA",
    importPath: "./components/call-for-speakers-cta",
  },
  {
    slug: "cta-call-for-sponsors-blue",
    name: "CallForSponsorsCTA",
    category: "CTA",
    exportName: "CallForSponsorsCTA",
    importPath: "./components/call-for-sponsors-cta",
  },
  {
    slug: "cta-call-for-volunteers-green",
    name: "CallForVolunteersCTA",
    category: "CTA",
    exportName: "CallForVolunteersCTA",
    importPath: "./components/call-for-volunteers-cta",
  },
  {
    slug: "blog-cards-grid",
    name: "BlogPreviewCards",
    category: "Blog",
    exportName: "BlogPreviewCards",
    importPath: "./components/blog-preview-cards",
  },
  {
    slug: "blog-post-article-body",
    name: "BlogPostArticle",
    category: "Blog",
    exportName: "BlogPostArticle",
    importPath: "./components/blog-post-article",
  },
  {
    slug: "content-about-colorcode-events",
    name: "ColorCodeEventsAbout",
    category: "Content",
    exportName: "ColorCodeEventsAbout",
    importPath: "./components/colorcode-events-about",
  },
  {
    slug: "content-two-column-origin-story",
    name: "HowItStarted",
    category: "Content",
    exportName: "HowItStarted",
    importPath: "./components/how-it-started",
  },
  {
    slug: "content-team-bio",
    name: "TeamBioBlock",
    category: "Content",
    exportName: "TeamBioBlock",
    importPath: "./components/team-bio-block",
  },
  {
    slug: "social-proof-photo-gallery",
    name: "EventPhotoGallery",
    category: "Social Proof",
    exportName: "EventPhotoGallery",
    importPath: "./components/event-photo-gallery",
  },
  {
    slug: "stats-event-details",
    name: "EventStatsBlock",
    category: "Stats",
    exportName: "EventStatsBlock",
    importPath: "./components/event-stats-block",
  },
  {
    slug: "cards-sponsors",
    name: "SponsorsGrid",
    category: "Cards",
    exportName: "SponsorsGrid",
    importPath: "./components/sponsors-grid",
  },
  {
    slug: "cta-get-tickets",
    name: "GetTicketsCTA",
    category: "CTA",
    exportName: "GetTicketsCTA",
    importPath: "./components/get-tickets-cta",
  },
  {
    slug: "custom-error-centered-card",
    name: "RegistrationErrorCard",
    category: "Custom",
    exportName: "RegistrationErrorCard",
    importPath: "./components/registration-error-card",
  },
  {
    slug: "content-legal",
    name: "LegalContent",
    category: "Content",
    exportName: "LegalContent",
    importPath: "./components/legal-content",
  },
  {
    slug: "content-checkout",
    name: "CheckoutContent",
    category: "Content",
    exportName: "CheckoutContent",
    importPath: "./components/checkout-content",
  },
  {
    slug: "content-team-bio-green",
    name: "TeamBioBenDunkle",
    category: "Content",
    exportName: "TeamBioBenDunkle",
    importPath: "./components/content-team-bio-green",
  },
  {
    slug: "content-team-bio-orange",
    name: "TeamBioRonBrennan",
    category: "Content",
    exportName: "TeamBioRonBrennan",
    importPath: "./components/content-team-bio-orange",
  },
  {
    slug: "content-team-bio-blue",
    name: "TeamBioTimBouchard",
    category: "Content",
    exportName: "TeamBioTimBouchard",
    importPath: "./components/content-team-bio-blue",
  },
  {
    slug: "blog-card-grid-two-col",
    name: "BlogPostGrid",
    category: "Blog",
    exportName: "BlogPostGrid",
    importPath: "./components/blog-card-grid-two-col",
  },
  {
    slug: "hero-blog-banner",
    name: "BlogPageBanner",
    category: "Hero",
    exportName: "BlogPageBanner",
    importPath: "./components/hero-blog-banner",
  },
  {
    slug: "content-blog-post-body",
    name: "BlogPostBody",
    category: "Blog",
    exportName: "BlogPostBody",
    importPath: "./components/content-blog-post-body",
  },
  {
    slug: "blog-post-article-content",
    name: "BlogPostArticle",
    category: "Blog",
    exportName: "BlogPostArticle",
    importPath: "./components/blog-post-article-content",
  },
  {
    slug: "navigation-logo-cta-bar",
    name: "SiteHeader",
    category: "Navigation",
    exportName: "SiteHeader",
    importPath: "./components/navigation-logo-cta-bar",
  },
  {
    slug: "cta-newsletter-signup-bar",
    name: "NewsletterSignupBar",
    category: "CTA",
    exportName: "NewsletterSignupBar",
    importPath: "./components/cta-newsletter-signup-bar",
  },
  {
    slug: "hero",
    name: "Hero",
    category: "Hero",
    exportName: "Hero",
    importPath: "./components/hero",
  },
  {
    slug: "navigation-buffalo-2025",
    name: "NavigationBuffalo2025",
    category: "Navigation",
    exportName: "NavigationBuffalo2025",
    importPath: "./components/navigation-buffalo-2025",
  },
  {
    slug: "stats-saturday",
    name: "StatsSaturday",
    category: "Stats",
    exportName: "StatsSaturday",
    importPath: "./components/stats-saturday",
  },
  {
    slug: "stats",
    name: "Stats",
    category: "Stats",
    exportName: "Stats",
    importPath: "./components/stats",
  },
  {
    slug: "stats-venue",
    name: "StatsVenue",
    category: "Stats",
    exportName: "StatsVenue",
    importPath: "./components/stats-venue",
  },
  {
    slug: "stats-schedule",
    name: "StatsSchedule",
    category: "Stats",
    exportName: "StatsSchedule",
    importPath: "./components/stats-schedule",
  },
  {
    slug: "stats-speakers",
    name: "StatsSpeakers",
    category: "Stats",
    exportName: "StatsSpeakers",
    importPath: "./components/stats-speakers",
  },
  {
    slug: "cta-subscribe-to-our-newsletter",
    name: "CtaSubscribeToOurNewsletter",
    category: "CTA",
    exportName: "CtaSubscribeToOurNewsletter",
    importPath: "./components/cta-subscribe-to-our-newsletter",
  },
  {
    slug: "content",
    name: "Content",
    category: "Content",
    exportName: "Content",
    importPath: "./components/content",
  },
  {
    slug: "cta-colorcode-buffalo-tickets-comi",
    name: "CtaColorcodeBuffaloTicketsComi",
    category: "CTA",
    exportName: "CtaColorcodeBuffaloTicketsComi",
    importPath: "./components/cta-colorcode-buffalo-tickets-comi",
  },
  {
    slug: "navigation-jump-to",
    name: "NavigationJumpTo",
    category: "Navigation",
    exportName: "NavigationJumpTo",
    importPath: "./components/navigation-jump-to",
  },
  {
    slug: "content-privacy-policy",
    name: "ContentPrivacyPolicy",
    category: "Content",
    exportName: "ContentPrivacyPolicy",
    importPath: "./components/content-privacy-policy",
  },
  {
    slug: "content-whoops",
    name: "ContentWhoops",
    category: "Content",
    exportName: "ContentWhoops",
    importPath: "./components/content-whoops",
  },
];
