export function CorvusHeader(props: Record<string, unknown>) {
  return (
    <header className="bg-surface-inverse text-on-brand-primary py-4">
      <div className="container-standard flex items-center justify-between">
        <a href="/" className="text-xl font-bold">
          {String(props.siteName ?? "")}
        </a>
        <nav className="hidden md:flex gap-6">
          {/* Navigation will be generated by --pass translate */}
        </nav>
      </div>
    </header>
  );
}
