/* eslint-disable */
// @ts-nocheck
// Auto-generated by extract-theme --pass componentize

export function CorvusHeader(props: Record<string, unknown>) {
  void props;
  return (
    <header className="bde-header-builder-18-108 bde-header-builder bde-header-builder--sticky bde-header-builder--sticky-scroll-slide bde-header-builder--overlay">
      <div className="bde-header-builder__container">
        <div className="bde-div-18-109 bde-div">
          <a
            className="bde-container-link-18-110 bde-container-link breakdance-link"
            href="/"
            target="_self"
            data-type="url"
          >
            <img
              className="bde-image2-18-111 bde-image2"
              src="/clone-assets/corvus/images/colorcode-events-logo.svg"
              alt="ColorCode Events"
              loading="lazy"
              sizes="(max-width: 1px) 100vw, 1px"
            />
          </a>
        </div>{" "}
        <div className="bde-div-18-112 bde-div">
          <div className="bde-button-18-113 bde-button">
            <a
              className="breakdance-link button-atom button-atom--custom bde-button__button"
              href="/buffalo/"
              target="_self"
              data-type="url"
            >
              <span className="button-atom__text">Buffalo 2026 Info</span>
            </a>
          </div>{" "}
          <div id="menu-toggle" className="bde-icon-18-114 bde-icon">
            <div className="bde-icon-icon breakdance-icon-atom">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
