import type React from "react";

export function CorvusHeader(props: Record<string, unknown>) {
  return (
    <header className="site-header">
      {/* corvus header — stub, to be regenerated by pipeline */}
      <nav className="nav container">
        <a href="/" className="nav-logo">
          {String(props.siteName ?? "")}
        </a>
      </nav>
    </header>
  );
}
