/**
 * Manifest-driven theme loader
 *
 * Auto-discovers pipeline-generated theme components from
 * theme manifest files and merges them into the global elements array.
 *
 * Currently a stub — when new themes are generated by the pipeline,
 * their showcase-registry.tsx entries will be imported here and
 * converted to ElementDefinition format.
 */

import type { ElementDefinition } from './index';

/**
 * Load ElementDefinition entries from pipeline-generated theme manifests.
 *
 * As new themes are generated, add their showcase registry imports here:
 *   import { novaElements } from '@platform/themes/nova/showcase';
 *   ...and merge into the returned array.
 */
export function loadThemeManifestElements(): ElementDefinition[] {
  // Pipeline-generated themes will be added here as they're created.
  // Each theme's showcase-registry.tsx exports entries with a single
  // theme key in their renders map, which gets merged into the
  // ElementDefinition format here.
  return [];
}
