/**
 * Atlas Theme — Component Manifest
 *
 * Auto-generated from reference analysis.
 * Maps blueprint metadata for tooling and showcase integration.
 */

import type { ComponentCategory } from '../../theme-system/src/types';

export interface ThemeComponentEntry {
  slug: string;
  name: string;
  category: ComponentCategory;
  exportName: string;
  importPath: string;
}

export const manifest: ThemeComponentEntry[] = [
  {
    slug: "navigation-top-bar",
    name: "TopNavBar",
    category: "Navigation",
    exportName: "TopNavBar",
    importPath: "./components/top-nav-bar",
  },
  {
    slug: "hero-full-bleed-text",
    name: "HeroFullBleed",
    category: "Hero",
    exportName: "HeroFullBleed",
    importPath: "./components/hero-full-bleed-text",
  },
  {
    slug: "hero-event-details-split",
    name: "EventDetailsBanner",
    category: "Hero",
    exportName: "EventDetailsBanner",
    importPath: "./components/hero-event-details-split",
  },
  {
    slug: "hero-page-title-banner",
    name: "PageTitleBanner",
    category: "Hero",
    exportName: "PageTitleBanner",
    importPath: "./components/hero-page-title-banner",
  },
  {
    slug: "cta-newsletter-signup",
    name: "NewsletterSignup",
    category: "CTA",
    exportName: "NewsletterSignup",
    importPath: "./components/cta-newsletter-signup",
  },
  {
    slug: "footer-multi-column",
    name: "SiteFooter",
    category: "Footer",
    exportName: "SiteFooter",
    importPath: "./components/footer-multi-column",
  },
  {
    slug: "cta-call-for-speakers",
    name: "CallForSpeakers",
    category: "CTA",
    exportName: "CallForSpeakers",
    importPath: "./components/cta-call-for-speakers",
  },
  {
    slug: "cta-call-for-sponsors",
    name: "CallForSponsors",
    category: "CTA",
    exportName: "CallForSponsors",
    importPath: "./components/cta-call-for-sponsors",
  },
  {
    slug: "cta-call-for-volunteers",
    name: "CallForVolunteers",
    category: "CTA",
    exportName: "CallForVolunteers",
    importPath: "./components/cta-call-for-volunteers",
  },
  {
    slug: "cta-get-tickets",
    name: "CtaGetTickets",
    category: "CTA",
    exportName: "CtaGetTickets",
    importPath: "./components/cta-get-tickets",
  },
  {
    slug: "blog-cards-grid",
    name: "BlogPreviewGrid",
    category: "Blog",
    exportName: "BlogPreviewGrid",
    importPath: "./components/blog-cards-grid",
  },
  {
    slug: "blog-post-article",
    name: "BlogPostArticle",
    category: "Blog",
    exportName: "BlogPostArticle",
    importPath: "./components/blog-post-article",
  },
  {
    slug: "content-about-events",
    name: "ColorCodeEventsAbout",
    category: "Content",
    exportName: "ColorCodeEventsAbout",
    importPath: "./components/content-about-events",
  },
  {
    slug: "content-two-column-origin-story",
    name: "HowItStartedSection",
    category: "Content",
    exportName: "HowItStartedSection",
    importPath: "./components/content-two-column-origin-story",
  },
  {
    slug: "cards-team-member",
    name: "TeamMemberCard",
    category: "Cards",
    exportName: "TeamMemberCard",
    importPath: "./components/cards-team-member",
  },
  {
    slug: "cards-sponsors",
    name: "SponsorsGrid",
    category: "Cards",
    exportName: "SponsorsGrid",
    importPath: "./components/cards-sponsors",
  },
  {
    slug: "stats-event",
    name: "EventStats",
    category: "Stats",
    exportName: "EventStats",
    importPath: "./components/stats-event",
  },
  {
    slug: "custom-photo-gallery-strip",
    name: "PhotoGalleryStrip",
    category: "Custom",
    exportName: "PhotoGalleryStrip",
    importPath: "./components/custom-photo-gallery-strip",
  },
  {
    slug: "custom-error-message-centered",
    name: "RegistrationErrorState",
    category: "Custom",
    exportName: "RegistrationErrorState",
    importPath: "./components/custom-error-message-centered",
  },
  {
    slug: "content-generic",
    name: "ContentBlock",
    category: "Content",
    exportName: "ContentBlock",
    importPath: "./components/content-generic",
  },
  {
    slug: "navigation-jump-to",
    name: "NavigationJumpTo",
    category: "Navigation",
    exportName: "NavigationJumpTo",
    importPath: "./components/navigation-jump-to",
  },
  {
    slug: "cards-team-member-green",
    name: "TeamMemberBenDunkle",
    category: "Cards",
    exportName: "TeamMemberBenDunkle",
    importPath: "./components/cards-team-member-green",
  },
  {
    slug: "cards-team-member-orange",
    name: "TeamMemberRonBrennan",
    category: "Cards",
    exportName: "TeamMemberRonBrennan",
    importPath: "./components/cards-team-member-orange",
  },
  {
    slug: "cards-team-member-blue",
    name: "TeamMemberTimBouchard",
    category: "Cards",
    exportName: "TeamMemberTimBouchard",
    importPath: "./components/cards-team-member-blue",
  },
  {
    slug: "footer-multi-column-links",
    name: "SiteFooter",
    category: "Footer",
    exportName: "SiteFooter",
    importPath: "./components/footer-multi-column-links",
  },
  {
    slug: "blog-cards-two-column",
    name: "BlogPostGrid",
    category: "Blog",
    exportName: "BlogPostGrid",
    importPath: "./components/blog-cards-two-column",
  },
  {
    slug: "cta-newsletter-inline-form",
    name: "NewsletterSubscribeCTA",
    category: "CTA",
    exportName: "NewsletterSubscribeCTA",
    importPath: "./components/cta-newsletter-inline-form",
  },
  {
    slug: "hero-page-banner",
    name: "PageBanner",
    category: "Hero",
    exportName: "PageBanner",
    importPath: "./components/hero-page-banner",
  },
  {
    slug: "blog-post-content-article",
    name: "BlogPostArticle",
    category: "Blog",
    exportName: "BlogPostArticle",
    importPath: "./components/blog-post-content-article",
  },
  {
    slug: "cta-newsletter-form",
    name: "NewsletterSignup",
    category: "CTA",
    exportName: "NewsletterSignup",
    importPath: "./components/cta-newsletter-form",
  },
  {
    slug: "blog-post-content-single",
    name: "BlogPostArticle",
    category: "Blog",
    exportName: "BlogPostArticle",
    importPath: "./components/blog-post-content-single",
  },
  {
    slug: "hero",
    name: "Hero",
    category: "Hero",
    exportName: "Hero",
    importPath: "./components/hero",
  },
  {
    slug: "navigation-buffalo-2025",
    name: "NavigationBuffalo2025",
    category: "Navigation",
    exportName: "NavigationBuffalo2025",
    importPath: "./components/navigation-buffalo-2025",
  },
  {
    slug: "stats-saturday",
    name: "StatsSaturday",
    category: "Stats",
    exportName: "StatsSaturday",
    importPath: "./components/stats-saturday",
  },
  {
    slug: "stats",
    name: "Stats",
    category: "Stats",
    exportName: "Stats",
    importPath: "./components/stats",
  },
  {
    slug: "stats-venue",
    name: "StatsVenue",
    category: "Stats",
    exportName: "StatsVenue",
    importPath: "./components/stats-venue",
  },
  {
    slug: "stats-schedule",
    name: "StatsSchedule",
    category: "Stats",
    exportName: "StatsSchedule",
    importPath: "./components/stats-schedule",
  },
  {
    slug: "stats-speakers",
    name: "StatsSpeakers",
    category: "Stats",
    exportName: "StatsSpeakers",
    importPath: "./components/stats-speakers",
  },
  {
    slug: "cta-subscribe-to-our-newsletter",
    name: "CtaSubscribeToOurNewsletter",
    category: "CTA",
    exportName: "CtaSubscribeToOurNewsletter",
    importPath: "./components/cta-subscribe-to-our-newsletter",
  },
  {
    slug: "content",
    name: "Content",
    category: "Content",
    exportName: "Content",
    importPath: "./components/content",
  },
  {
    slug: "cta-colorcode-buffalo-tickets-comi",
    name: "CtaColorcodeBuffaloTicketsComi",
    category: "CTA",
    exportName: "CtaColorcodeBuffaloTicketsComi",
    importPath: "./components/cta-colorcode-buffalo-tickets-comi",
  },
  {
    slug: "content-privacy-policy",
    name: "ContentPrivacyPolicy",
    category: "Content",
    exportName: "ContentPrivacyPolicy",
    importPath: "./components/content-privacy-policy",
  },
  {
    slug: "content-checkout",
    name: "ContentCheckout",
    category: "Content",
    exportName: "ContentCheckout",
    importPath: "./components/content-checkout",
  },
  {
    slug: "content-whoops",
    name: "ContentWhoops",
    category: "Content",
    exportName: "ContentWhoops",
    importPath: "./components/content-whoops",
  },
];
