import type { DeepPartialThemeConfig } from '@platform/theme-system';
import { siriusRegistry, siriusDefaultConfig } from '@platform/themes/sirius';

/**
 * Test site theme configuration
 * Generated by /pipeline.ingest
 */
export const themeConfig: DeepPartialThemeConfig = {
  componentRegistry: siriusRegistry,
  ...siriusDefaultConfig,
  colors: {
    ...siriusDefaultConfig.colors,
    surface: {
      ...siriusDefaultConfig.colors?.surface,
      inverse: '#111111',
    },
  },
};
