/**
 * Cygnus Theme
 *
 * Generated by /pipeline.stitch-design
 * Stitch project: Cygnus Design Print Signage Website (id: 5882758319668068405)
 * Trade type: Design, Print & Signage
 *
 * Dark mode theme — Press-Black canvas, Signal Orange primary, Craft Green secondary.
 * Designed for bold, graphic-led creative industry businesses.
 *
 * Sites using Cygnus: mad-graphics
 */

import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const cygnusRegistry: ComponentRegistry = {
  theme: "cygnus",
  heroVariant: "image-overlay",
  headerVariant: "dark",
  cardVariant: "standard",
  sectionVariant: "dark-accent",
};

export const cygnusDefaultConfig: DeepPartialThemeConfig = {
  colors: {
    brand: {
      primary: '#f7941d',
      primaryHover: '#e8850a',
      secondary: '#5ba829',
      accent: '#dec498',
      onPrimary: '#2d1600',
    },
    surface: {
      background: '#131313',
      foreground: '#e5e2e1',
      secondaryForeground: '#b8b4b0',
      tertiaryForeground: '#8c8884',
      muted: '#201f1f',
      mutedForeground: '#9a9490',
      card: '#1c1b1b',
      cardBorder: '#544435',
      subtle: '#201f1f',
      subtleBorder: '#544435',
    },
    semantic: {
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
    overlay: {
      dark: 'rgba(0,0,0,0.8)',
      light: 'rgba(255,255,255,0.8)',
      primary: 'rgba(247,148,29,0.8)',
    },
  },
};

registerTheme({ name: 'cygnus', label: 'Cygnus', config: cygnusDefaultConfig });
