// Must be imported before reading getRegisteredThemes()
// Guarantees theme packages execute registerTheme() regardless of tree-shaking
// AUTO-GENERATED by tools/sync-themes.ts — do not edit manually
import "@platform/themes/cygnus";
import "@platform/themes/orion";
import "@platform/themes/solaris";
import "@platform/themes/vega";
