// Must be imported before reading getRegisteredThemes()
// Guarantees theme packages execute registerTheme() regardless of tree-shaking
// AUTO-GENERATED by tools/sync-themes.ts — do not edit manually
import "@platform/themes/atlas";
import "@platform/themes/corvus";
import "@platform/themes/lyra";
import "@platform/themes/polaris";
import "@platform/themes/nova";
import "@platform/themes/orion";
import "@platform/themes/sirius";
import "@platform/themes/vega";
