#!/usr/bin/env bash
# SessionEnd hook — writes a minimal placeholder if session-wrap-up.md is absent.
# Called by Claude Code SessionEnd hook with JSON payload on stdin.

set -euo pipefail

PAYLOAD=$(cat)
CWD=$(echo "$PAYLOAD" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('cwd',''))" 2>/dev/null || echo "")

# Only act on local-business-platform sessions
if [[ "$CWD" != *"local-business-platform"* ]]; then
  exit 0
fi

PROJECT_ROOT="/Users/rickywilson/Sites/local-business-platform"
SESSIONS_DIR="$PROJECT_ROOT/output/sessions"

# Find most recent session folder (pointer file takes priority)
SESSION_POINTER="$SESSIONS_DIR/.current-session"
if [[ -f "$SESSION_POINTER" ]]; then
  SESSION_NAME=$(cat "$SESSION_POINTER")
  SESSION_DIR="$SESSIONS_DIR/$SESSION_NAME"
else
  SESSION_DIR=$(ls -dt "$SESSIONS_DIR"/*/[0-9]*/ 2>/dev/null | head -1 | tr -d '\n')
fi

[[ -z "$SESSION_DIR" ]] || [[ ! -d "$SESSION_DIR" ]] && exit 0

WRAP_UP_FILE="$SESSION_DIR/session-wrap-up.md"
[[ -f "$WRAP_UP_FILE" ]] && exit 0  # already written — nothing to do

FOLDER_NAME=$(basename "$SESSION_DIR")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_LOG=$(cd "$PROJECT_ROOT" && git log --oneline -10 2>/dev/null || echo "(no commits found)")

cat > "$WRAP_UP_FILE" << WRAPEOF
# Session Wrap-Up: $FOLDER_NAME

**Date:** $(date +%Y-%m-%d)
**Generated by:** SessionEnd hook (placeholder — /wrap-up-session was not run)
**Status:** Incomplete

> This is an auto-generated placeholder. Run \`/wrap-up-session\` to replace it
> with a proper synthesized summary.

## Recent Commits (at session end)

\`\`\`
$GIT_LOG
\`\`\`

_Generated at ${TIMESTAMP}_
WRAPEOF
