interface AboutPageProps {
  [key: string]: unknown;
}

export function CorvusAboutPage(props: AboutPageProps) {
  void props;
  return (
    <main className="page-about">
      {/* corvus about layout — stub, to be regenerated by pipeline */}
    </main>
  );
}
