/* eslint-disable */
// @ts-nocheck
// Auto-generated by extract-theme --pass componentize
// This is a clone-fidelity component — not a production template.
// Run extract-theme --pass strip to replace content with props.

interface AboutPageProps {
  [key: string]: unknown;
}

export function CorvusAboutPage(props: AboutPageProps) {
  void props;
  return (
    <>
      {/* header extracted to component */}
      <section className="bde-section-58-100 bde-section">
        <div className="section-container">
          <div className="bde-div-58-101 bde-div">
            <div className="bde-columns-58-102 bde-columns">
              <div className="bde-column-58-103 bde-column">
                <h1 className="bde-heading-58-104 bde-heading">
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span>About
                </h1>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bde-section-58-134 bde-section">
        <div className="section-container">
          <div className="bde-columns-58-135 bde-columns">
            <div className="bde-column-58-136 bde-column">
              <h2 className="bde-heading-58-144 bde-heading">{props.sectionTitle}</h2>
            </div>{" "}
            <div className="bde-column-58-138 bde-column"></div>
          </div>{" "}
          <div className="bde-columns-58-139 bde-columns">
            <div className="bde-column-58-140 bde-column">
              <img
                className="bde-image2-58-141 bde-image2"
                src={props.imageSrc}
                loading="lazy"
                srcSet="images/row-magenta-arrows.png 590w, images/row-magenta-arrows-300x33.png 300w"
                sizes="(max-width: 590px) 100vw, 590px"
                data-entrance="slideLeft"
              />
            </div>{" "}
            <div className="bde-column-58-142 bde-column">
              <div className="bde-rich-text-58-143 bde-rich-text breakdance-rich-text-styles">
                <p>{props.body}</p>
                <p>{props.description}</p>
                <p>{props.bodyText}</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bde-section-58-145 bde-section">
        <div className="section-container">
          <div className="bde-div-58-146 bde-div">
            <div className="bde-columns-58-147 bde-columns">
              <div className="bde-column-58-148 bde-column">
                <div className="bde-div-58-149 bde-div">
                  <div className="bde-image-58-150 bde-image" data-entrance="slideLeft">
                    <figure className="breakdance-image breakdance-image--35">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.heroImageSrc}
                            width="200"
                            height="200"
                            srcSet="images/shape-arrow-purple.png 200w, images/shape-arrow-purple-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-151 bde-image" data-entrance="slideRight">
                    <figure className="breakdance-image breakdance-image--29">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.cardImageSrc}
                            width="200"
                            height="200"
                            srcSet="images/shape-yellow-box.png 200w, images/shape-yellow-box-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-152 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--30">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.sectionImageSrc}
                            width="200"
                            height="200"
                            srcSet="images/shape-magenta-circle.png 200w, images/shape-magenta-circle-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-153 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--62">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc5}
                            width="334"
                            height="334"
                            srcSet="images/ben-dunkle.jpg 334w, images/ben-dunkle-300x300.jpg 300w, images/ben-dunkle-150x150.jpg 150w"
                            sizes="(max-width: 334px) 100vw, 334px"
                            alt="Ben Dunkle"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>{" "}
              <div className="bde-column-58-154 bde-column">
                <h2 className="bde-heading-58-155 bde-heading">{props.sectionTitle2}</h2>{" "}
                <h4 className="bde-heading-58-167 bde-heading">{props.sectionTitle5}</h4>{" "}
                <div className="bde-text-58-156 bde-text">
                  I'm a teacher, designer and (sometimes) artist in the Buffalo, NY area who loves
                  making icons and learning and teaching about the web. Ben is "famously" known for
                  being the designer of the Dashicons in the WordPress dashboard.
                </div>{" "}
                <div className="bde-button-58-158 bde-button">
                  <a
                    className="breakdance-link button-atom button-atom--text bde-button__button"
                    href={props.linkedinUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                  >
                    <span className="button-atom__text">LinkedIn</span>
                    <span className="button-atom__icon-wrapper">
                      <svg
                        className="un-arrow-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        viewBox="0 0 32 32"
                      >
                        <g
                          fill="none"
                          strokeWidth="1.9"
                          strokeLinejoin="round"
                          stroke-miterlimit="10"
                        >
                          <circle
                            className="un-arrow-icon_circle"
                            cx="16"
                            cy="16"
                            r="15.12"
                          ></circle>
                          <path
                            className="un-arrow-icon_arrow"
                            d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"
                          ></path>
                        </g>
                      </svg>
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>{" "}
          <div className="bde-div-58-168 bde-div">
            <div className="bde-columns-58-169 bde-columns">
              <div className="bde-column-58-176 bde-column">
                <h2 className="bde-heading-58-177 bde-heading">{props.sectionTitle3}</h2>{" "}
                <h4 className="bde-heading-58-178 bde-heading">{props.sectionTitle6}</h4>{" "}
                <div className="bde-text-58-179 bde-text">
                  With over 20 years of experience in business operations, management, marketing,
                  and tech, Ron's been the go-to guy for helping companies scale. He's seen
                  firsthand the highs and lows of guiding a business through growth spurts and
                  tricky markets. In 2013, he founded CANI Marketing Group so he could use those
                  insights and learned experiences to help others grow their business.
                </div>{" "}
                <div className="bde-button-58-180 bde-button">
                  <a
                    className="breakdance-link button-atom button-atom--text bde-button__button"
                    href="#"
                    target="_blank"
                    data-type="url"
                  >
                    <span className="button-atom__text">CANI Marketing Group</span>
                    <span className="button-atom__icon-wrapper">
                      <svg
                        className="un-arrow-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        viewBox="0 0 32 32"
                      >
                        <g
                          fill="none"
                          strokeWidth="1.9"
                          strokeLinejoin="round"
                          stroke-miterlimit="10"
                        >
                          <circle
                            className="un-arrow-icon_circle"
                            cx="16"
                            cy="16"
                            r="15.12"
                          ></circle>
                          <path
                            className="un-arrow-icon_arrow"
                            d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"
                          ></path>
                        </g>
                      </svg>
                    </span>
                  </a>
                </div>{" "}
                <div className="bde-button-58-181 bde-button">
                  <a
                    className="breakdance-link button-atom button-atom--text bde-button__button"
                    href={props.linkedinUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                  >
                    <span className="button-atom__text">LinkedIn</span>
                    <span className="button-atom__icon-wrapper">
                      <svg
                        className="un-arrow-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        viewBox="0 0 32 32"
                      >
                        <g
                          fill="none"
                          strokeWidth="1.9"
                          strokeLinejoin="round"
                          stroke-miterlimit="10"
                        >
                          <circle
                            className="un-arrow-icon_circle"
                            cx="16"
                            cy="16"
                            r="15.12"
                          ></circle>
                          <path
                            className="un-arrow-icon_arrow"
                            d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"
                          ></path>
                        </g>
                      </svg>
                    </span>
                  </a>
                </div>
              </div>{" "}
              <div className="bde-column-58-170 bde-column">
                <div className="bde-div-58-171 bde-div">
                  <div className="bde-image-58-172 bde-image" data-entrance="slideLeft">
                    <figure className="breakdance-image breakdance-image--24">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc6}
                            width="200"
                            height="200"
                            srcSet="images/shape-green-half-circle.png 200w, images/shape-green-half-circle-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-173 bde-image" data-entrance="slideRight">
                    <figure className="breakdance-image breakdance-image--29">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc7}
                            width="200"
                            height="200"
                            srcSet="images/shape-yellow-box.png 200w, images/shape-yellow-box-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-174 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--35">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc8}
                            width="200"
                            height="200"
                            srcSet="images/shape-arrow-purple.png 200w, images/shape-arrow-purple-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-175 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--61">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc9}
                            width="800"
                            height="800"
                            srcSet="images/ron-brennan.jpg 800w, images/ron-brennan-300x300.jpg 300w, images/ron-brennan-150x150.jpg 150w, images/ron-brennan-768x768.jpg 768w, images/ron-brennan-400x400.jpg 400w, images/ron-brennan-600x600.jpg 600w"
                            sizes="(max-width: 800px) 100vw, 800px"
                            alt="Ron Brennan"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>
            </div>
          </div>{" "}
          <div className="bde-div-58-182 bde-div">
            <div className="bde-columns-58-183 bde-columns">
              <div className="bde-column-58-190 bde-column">
                <div className="bde-div-58-191 bde-div">
                  <div className="bde-image-58-192 bde-image" data-entrance="slideLeft">
                    <figure className="breakdance-image breakdance-image--30">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc10}
                            width="200"
                            height="200"
                            srcSet="images/shape-magenta-circle.png 200w, images/shape-magenta-circle-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-193 bde-image" data-entrance="slideRight">
                    <figure className="breakdance-image breakdance-image--26">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc11}
                            width="200"
                            height="200"
                            srcSet="images/shape-orange-arrow.png 200w, images/shape-orange-arrow-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-194 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--29">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc12}
                            width="200"
                            height="200"
                            srcSet="images/shape-yellow-box.png 200w, images/shape-yellow-box-150x150.png 150w"
                            sizes="(max-width: 200px) 100vw, 200px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>{" "}
                  <div className="bde-image-58-195 bde-image" data-entrance="slideUp">
                    <figure className="breakdance-image breakdance-image--621">
                      <div className="breakdance-image-container">
                        <div className="breakdance-image-clip">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc13}
                            width="719"
                            height="719"
                            srcSet="images/tim-bouchard-luminus-headshot.jpg 719w, images/tim-bouchard-luminus-headshot-300x300.jpg 300w, images/tim-bouchard-luminus-headshot-150x150.jpg 150w"
                            sizes="(max-width: 719px) 100vw, 719px"
                          />
                        </div>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>{" "}
              <div className="bde-column-58-184 bde-column">
                <h2 className="bde-heading-58-185 bde-heading">{props.sectionTitle4}</h2>{" "}
                <h4 className="bde-heading-58-186 bde-heading">{props.sectionTitle7}</h4>{" "}
                <div className="bde-text-58-187 bde-text">
                  Tim is the founder, owner and CEO of Luminus, a marketing agency in Buffalo, NY
                  with a digital edge. Luminus specializes in producing strategic high performance
                  websites and successful digital marketing campaigns that are relevant for
                  converting audiences. He is a graduate of UB's Media Study program with a
                  background as a designer, web developer and marketing consultant for over 20
                  years.
                </div>{" "}
                <div className="bde-button-58-188 bde-button">
                  <a
                    className="breakdance-link button-atom button-atom--text bde-button__button"
                    href="#"
                    target="_blank"
                    data-type="url"
                  >
                    <span className="button-atom__text">Luminus Agency</span>
                    <span className="button-atom__icon-wrapper">
                      <svg
                        className="un-arrow-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        viewBox="0 0 32 32"
                      >
                        <g
                          fill="none"
                          strokeWidth="1.9"
                          strokeLinejoin="round"
                          stroke-miterlimit="10"
                        >
                          <circle
                            className="un-arrow-icon_circle"
                            cx="16"
                            cy="16"
                            r="15.12"
                          ></circle>
                          <path
                            className="un-arrow-icon_arrow"
                            d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"
                          ></path>
                        </g>
                      </svg>
                    </span>
                  </a>
                </div>{" "}
                <div className="bde-button-58-189 bde-button">
                  <a
                    className="breakdance-link button-atom button-atom--text bde-button__button"
                    href={props.linkedinUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                  >
                    <span className="button-atom__text">LinkedIn</span>
                    <span className="button-atom__icon-wrapper">
                      <svg
                        className="un-arrow-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        width="32"
                        height="32"
                        viewBox="0 0 32 32"
                      >
                        <g
                          fill="none"
                          strokeWidth="1.9"
                          strokeLinejoin="round"
                          stroke-miterlimit="10"
                        >
                          <circle
                            className="un-arrow-icon_circle"
                            cx="16"
                            cy="16"
                            r="15.12"
                          ></circle>
                          <path
                            className="un-arrow-icon_arrow"
                            d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"
                          ></path>
                        </g>
                      </svg>
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bde-section-40-100 bde-section">
        <div className="section-container">
          <div className="bde-div-40-101 bde-div">
            <div className="bde-div-40-102 bde-div">
              <h4 className="bde-heading-40-103 bde-heading">{props.sectionTitle8}</h4>{" "}
              <div className="bde-text-40-104 bde-text">
                The latest event news, articles, and resources, sent to your inbox.
              </div>
            </div>{" "}
            <div className="bde-form-builder-40-105 bde-form-builder">
              <form
                id="contact-form105"
                className="breakdance-form breakdance-form--horizontal"
                data-steps="0"
              >
                <div className="breakdance-form-field breakdance-form-field--email breakdance-form-field__hide-label">
                  <input
                    className="breakdance-form-field__input"
                    id="newsletter_email"
                    aria-describedby="newsletter_email"
                    type="email"
                    name="fields[newsletter_email]"
                    placeholder="{props.email} *"
                    value=""
                    required={true}
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-field--hpinput">
                  <label className="breakdance-form-field__label" htmlFor="hpname">
                    HP Name
                  </label>
                  <input
                    className="breakdance-form-field__input"
                    id="hpname"
                    aria-describedby="hpname"
                    type="hpinput"
                    name="fields[hpname]"
                    placeholder=""
                    value=""
                    autoComplete="off"
                    tabIndex="-1"
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-footer">
                  <button
                    type="submit"
                    className="button-atom button-atom--primary breakdance-form-button breakdance-form-button__submit"
                  >
                    <span className="button-atom__text">Submit</span>
                  </button>
                  <input type="hidden" name="form_id" value="105" />
                  <input type="hidden" name="post_id" value="40" />
                </div>
              </form>
            </div>
          </div>{" "}
          <div className="bde-columns-40-106 bde-columns">
            <div className="bde-column-40-107 bde-column">
              <div className="bde-text-40-108 bde-text">Events</div>{" "}
              <a
                className="bde-text-link-40-109 bde-text-link breakdance-link"
                href="/buffalo/"
                target="_self"
                data-type="url"
              >
                ColorCode Buffalo
              </a>
            </div>{" "}
            <div className="bde-column-40-110 bde-column">
              <div className="bde-text-40-111 bde-text">Support</div>{" "}
              <a
                className="bde-text-link-40-112 bde-text-link breakdance-link"
                href="/call-for-sponsors/"
                target="_self"
                data-type="url"
              >
                Call For Sponsors
              </a>{" "}
              <a
                className="bde-text-link-40-130 bde-text-link breakdance-link"
                href="/call-for-speakers/"
                target="_self"
                data-type="url"
              >
                Call For Speakers
              </a>{" "}
              <a
                className="bde-text-link-40-113 bde-text-link breakdance-link"
                href="/call-for-volunteers/"
                target="_self"
                data-type="url"
              >
                Call For Volunteers
              </a>
            </div>{" "}
            <div className="bde-column-40-114 bde-column">
              <div className="bde-text-40-115 bde-text">Legal</div>{" "}
              <a
                className="bde-text-link-40-116 bde-text-link breakdance-link"
                href="/code-of-conduct/"
                target="_self"
                data-type="url"
              >
                Code of Conduct
              </a>{" "}
              <a
                className="bde-text-link-40-117 bde-text-link breakdance-link"
                href="/privacy-policy/"
                target="_self"
                data-type="url"
              >
                Privacy
              </a>
            </div>{" "}
            <div className="bde-column-40-119 bde-column">
              <div className="bde-text-40-120 bde-text">Company</div>{" "}
              <a
                className="bde-text-link-40-121 bde-text-link breakdance-link"
                href="/about/"
                target="_self"
                data-type="url"
              >
                About
              </a>{" "}
              <a
                className="bde-text-link-40-129 bde-text-link breakdance-link"
                href="/contact/"
                target="_self"
                data-type="url"
              >
                Contact
              </a>
            </div>{" "}
            <div className="bde-column-40-123 bde-column">
              <img
                className="bde-image2-40-124 bde-image2"
                src={props.imageSrc14}
                alt="ColorCode Events"
                loading="lazy"
                sizes="(max-width: 1px) 100vw, 1px"
              />
            </div>
          </div>{" "}
          <div className="bde-fancy-divider-40-125 bde-fancy-divider">
            <div className="bde-fancy-divider__wrapper">
              <div className="bde-fancy-divider__separator   "></div>
            </div>
          </div>{" "}
          <div className="bde-div-40-126 bde-div">
            <p className="de-cry-40-127 de-cry">{props.paragraph}</p>{" "}
            <div className="bde-social-icons-40-128 bde-social-icons">
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-facebook"
                href={props.facebookUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="facebook"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-instagram"
                href={props.instagramUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="instagram"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-twitter"
                href={props.xUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="twitter"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 512 512">
                  <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-linkedin"
                href={props.linkedinUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="linkedin"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="-4 -2 32 32">
                  <path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
