interface BlogListPageProps {
  [key: string]: unknown;
}

export function CorvusBlogListPage(props: BlogListPageProps) {
  void props;
  return (
    <main className="page-blog-list">
      {/* corvus blog-list layout — stub, to be regenerated by pipeline */}
    </main>
  );
}
