/* eslint-disable */
// @ts-nocheck
// Auto-generated by extract-theme --pass componentize
// This is a clone-fidelity component — not a production template.
// Run extract-theme --pass strip to replace content with props.

interface BlogPostPageProps {
  [key: string]: unknown;
}

export function CorvusBlogPostPage(props: BlogPostPageProps) {
  void props;
  return (
    <>
      {/* header extracted to component */}
      <section className="bde-section-171-100 bde-section">
        <div className="section-container">
          <div className="bde-div-171-101 bde-div">
            <div className="bde-columns-171-102 bde-columns">
              <div className="bde-column-171-103 bde-column">
                <h2 className="bde-heading-171-104 bde-heading">
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span> Blog
                </h2>
              </div>
            </div>
          </div>{" "}
          <div className="bde-div-171-105 bde-div">
            <div className="bde-columns-171-106 bde-columns">
              <div className="bde-column-171-107 bde-column">
                <h1 className="bde-heading-171-109 bde-heading">
                  The Journey to Our First ColorCode: Buffalo
                </h1>{" "}
                <div className="bde-text-171-110 bde-text">April 28, 2025</div>{" "}
                <div className="bde-rich-text-171-111 bde-rich-text breakdance-rich-text-styles">
                  <p>
                    <img
                      loading="lazy"
                      decoding="async"
                      className="alignright wp-image-97 "
                      src="images/colorcode-buffalo-share-1024x605.jpg"
                      alt=""
                      width="501"
                      height="296"
                      srcSet="images/colorcode-buffalo-share-1024x605.jpg 1024w, images/colorcode-buffalo-share-300x177.jpg 300w, images/colorcode-buffalo-share-768x454.jpg 768w, images/colorcode-buffalo-share.jpg 1150w"
                      sizes="auto, (max-width: 501px) 100vw, 501px"
                    />
                    It&#8217;s crazy to think about the last year in the design, web dev, WordPress,
                    and even marketing world in general. Between #WPDrama and AI taking over along
                    with the stubborn effects of COVID and public gatherings lingering, it&#8217;s
                    been a rough couple months (maybe years).
                  </p>
                  <p>
                    In 2023, my agency{" "}
                    <a href="https://luminus.agency" target="_blank" rel="noopener">
                      Luminus
                    </a>{" "}
                    sponsored WordCamp Buffalo, I was personally unable to attend, but my team did
                    and noted how great it was to see in-person events bouncing back. The event
                    still didn&#8217;t quite &#8220;hit&#8221; the way it should as that post-COVID
                    effect was still hampering the success of all events starting to come back. So
                    in 2024 our agency got involved and took on the entire branding and marketing
                    side of WordCamp Buffalo. The event looked the part and we all had a blast there
                    and met great people, but it still felt underwhelming for some reason.
                  </p>
                  <p>
                    So I joined up with Ron &amp; Ben as a co-organizer and as early as July 2024,
                    we started planning for WordCamp Buffalo 2025. Well, that got derailed in
                    September lol. Things got dicey with WordCamp Central, sponsors, wordpress.org
                    logins, etc etc. We were already wondering what else we might be able to do if
                    we attempted an independent event. #WPDrama pushed us over the edge and by
                    October 2024, we had started planning for ColorCode.
                  </p>
                  <p>
                    With the barriers torn down, we were able to accomplish a number of things we
                    desperately wanted to do:
                  </p>
                  <ol>
                    <li>Expand event topics beyond WordPress specific topics</li>
                    <li>
                      Brand the event and build assets exactly how we wanted without trademark or
                      platform restrictions
                    </li>
                    <li>Build sponsorship relationships directly rather than being handed them</li>
                    <li>
                      Run the planning and logistics of the event and promotional marketing the way
                      we wanted to
                    </li>
                  </ol>
                  <p>
                    Ron and Ben had run nearly 10 years worth of WordCamps, they didn&#8217;t go
                    into this blind, but we still had to start from scratch.
                  </p>
                  <p>
                    <img
                      loading="lazy"
                      decoding="async"
                      className="alignleft wp-image-81 size-medium"
                      src="images/event-sponsor-luminus-300x300.jpg"
                      alt=""
                      width="300"
                      height="300"
                      srcSet="images/event-sponsor-luminus-300x300.jpg 300w, images/event-sponsor-luminus-1024x1024.jpg 1024w, images/event-sponsor-luminus-150x150.jpg 150w, images/event-sponsor-luminus-768x768.jpg 768w, images/event-sponsor-luminus-1536x1536.jpg 1536w, images/event-sponsor-luminus-400x400.jpg 400w, images/event-sponsor-luminus-600x600.jpg 600w, images/event-sponsor-luminus.jpg 2000w"
                      sizes="auto, (max-width: 300px) 100vw, 300px"
                    />
                    It&#8217;s been a long 10 months of planning, pivoting, and work to get to this
                    point. ColorCode: Buffalo 2025 is THIS WEEK and we have a full slate of amazing
                    speakers, a sponsor roster that nearly fully funded the entire event allowing us
                    to keep ticket costs low, and over 100 attendees ready to network, learn, and
                    have fun together!
                  </p>
                  <p>
                    This process has been a rollercoaster ride, but like any good rollercoaster,
                    we&#8217;re having a blast and we&#8217;re ready to do it again!
                  </p>
                  <p>
                    We believe in the power of the user, design, development, and marketing
                    communities coming together.
                  </p>
                  <p>
                    There&#8217;s more to this story and we can&#8217;t wait to build upon this
                    foundation.
                  </p>
                  <p>Thanks for coming along for the ride!</p>
                  <p>&#8211; Tim</p>
                </div>{" "}
                <a
                  className="bde-text-link-171-112 bde-text-link breakdance-link"
                  href="/blog/"
                  target="_self"
                  data-type="url"
                >
                  « Back To Blog
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bde-section-40-100 bde-section">
        <div className="section-container">
          <div className="bde-div-40-101 bde-div">
            <div className="bde-div-40-102 bde-div">
              <h4 className="bde-heading-40-103 bde-heading">Subscribe to our Newsletter</h4>{" "}
              <div className="bde-text-40-104 bde-text">
                The latest event news, articles, and resources, sent to your inbox.
              </div>
            </div>{" "}
            <div className="bde-form-builder-40-105 bde-form-builder">
              <form
                id="contact-form105"
                className="breakdance-form breakdance-form--horizontal"
                data-steps="0"
              >
                <div className="breakdance-form-field breakdance-form-field--email breakdance-form-field__hide-label">
                  <input
                    className="breakdance-form-field__input"
                    id="newsletter_email"
                    aria-describedby="newsletter_email"
                    type="email"
                    name="fields[newsletter_email]"
                    placeholder="emailname@example.com *"
                    value=""
                    required={true}
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-field--hpinput">
                  <label className="breakdance-form-field__label" htmlFor="hpname">
                    HP Name
                  </label>
                  <input
                    className="breakdance-form-field__input"
                    id="hpname"
                    aria-describedby="hpname"
                    type="hpinput"
                    name="fields[hpname]"
                    placeholder=""
                    value=""
                    autoComplete="off"
                    tabIndex="-1"
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-footer">
                  <button
                    type="submit"
                    className="button-atom button-atom--primary breakdance-form-button breakdance-form-button__submit"
                  >
                    <span className="button-atom__text">Submit</span>
                  </button>
                  <input type="hidden" name="form_id" value="105" />
                  <input type="hidden" name="post_id" value="40" />
                </div>
              </form>
            </div>
          </div>{" "}
          <div className="bde-columns-40-106 bde-columns">
            <div className="bde-column-40-107 bde-column">
              <div className="bde-text-40-108 bde-text">Events</div>{" "}
              <a
                className="bde-text-link-40-109 bde-text-link breakdance-link"
                href="/buffalo/"
                target="_self"
                data-type="url"
              >
                ColorCode Buffalo
              </a>
            </div>{" "}
            <div className="bde-column-40-110 bde-column">
              <div className="bde-text-40-111 bde-text">Support</div>{" "}
              <a
                className="bde-text-link-40-112 bde-text-link breakdance-link"
                href="/call-for-sponsors/"
                target="_self"
                data-type="url"
              >
                Call For Sponsors
              </a>{" "}
              <a
                className="bde-text-link-40-130 bde-text-link breakdance-link"
                href="/call-for-speakers/"
                target="_self"
                data-type="url"
              >
                Call For Speakers
              </a>{" "}
              <a
                className="bde-text-link-40-113 bde-text-link breakdance-link"
                href="/call-for-volunteers/"
                target="_self"
                data-type="url"
              >
                Call For Volunteers
              </a>
            </div>{" "}
            <div className="bde-column-40-114 bde-column">
              <div className="bde-text-40-115 bde-text">Legal</div>{" "}
              <a
                className="bde-text-link-40-116 bde-text-link breakdance-link"
                href="/code-of-conduct/"
                target="_self"
                data-type="url"
              >
                Code of Conduct
              </a>{" "}
              <a
                className="bde-text-link-40-117 bde-text-link breakdance-link"
                href="/privacy-policy/"
                target="_self"
                data-type="url"
              >
                Privacy
              </a>
            </div>{" "}
            <div className="bde-column-40-119 bde-column">
              <div className="bde-text-40-120 bde-text">Company</div>{" "}
              <a
                className="bde-text-link-40-121 bde-text-link breakdance-link"
                href="/about/"
                target="_self"
                data-type="url"
              >
                About
              </a>{" "}
              <a
                className="bde-text-link-40-129 bde-text-link breakdance-link"
                href="/contact/"
                target="_self"
                data-type="url"
              >
                Contact
              </a>
            </div>{" "}
            <div className="bde-column-40-123 bde-column">
              <img
                className="bde-image2-40-124 bde-image2"
                src="images/colorcode-events-logo.svg"
                alt="ColorCode Events"
                loading="lazy"
                sizes="(max-width: 1px) 100vw, 1px"
              />
            </div>
          </div>{" "}
          <div className="bde-fancy-divider-40-125 bde-fancy-divider">
            <div className="bde-fancy-divider__wrapper">
              <div className="bde-fancy-divider__separator   "></div>
            </div>
          </div>{" "}
          <div className="bde-div-40-126 bde-div">
            <p className="de-cry-40-127 de-cry">
              &copy; 2026 ColorCode Events. All Rights Reserved. Website by{" "}
              <a href="https://luminus.agency" target="_blank">
                Luminus
              </a>
            </p>{" "}
            <div className="bde-social-icons-40-128 bde-social-icons">
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-facebook"
                href="https://www.facebook.com/colorcodeevents/"
                target="_blank"
                data-type="url"
                aria-label="facebook"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-instagram"
                href="https://www.instagram.com/hellocolorcode"
                target="_blank"
                data-type="url"
                aria-label="instagram"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-twitter"
                href="https://x.com/ColorCodeEvents"
                target="_blank"
                data-type="url"
                aria-label="twitter"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 512 512">
                  <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-linkedin"
                href="https://www.linkedin.com/company/105866867"
                target="_blank"
                data-type="url"
                aria-label="linkedin"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="-4 -2 32 32">
                  <path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </section>
      <div className="breakdance">
        <div className="bde-popup-85-100 bde-popup">
          <div
            className="breakdance-popup
    "
            data-breakdance-popup-id="85"
          >
            <div className="breakdance-popup-content">
              <section className="bde-section-85-101 bde-section">
                <div className="section-container">
                  <img
                    className="bde-image2-85-102 bde-image2"
                    src="images/colorcode-events-logo.svg"
                    alt="ColorCode Events"
                    loading="lazy"
                    sizes="(max-width: 1px) 100vw, 1px"
                  />
                </div>
              </section>{" "}
              <section className="bde-section-85-103 bde-section">
                <div className="section-container">
                  <div className="bde-columns-85-104 bde-columns">
                    <div className="bde-column-85-105 bde-column">
                      <h1 className="bde-heading-85-106 bde-heading">
                        ColorCode: Buffalo Tickets Coming Soon!
                      </h1>{" "}
                      <div className="bde-text-85-114 bde-text">
                        We are currently finalizing vendors & budgets before launching ticket sales
                        in March 2026. Add your info below or follow us on social media to get
                        notified when tickets go live!
                      </div>{" "}
                      <div className="bde-form-builder-85-113 bde-form-builder">
                        <form
                          id="contact-form113"
                          className="breakdance-form breakdance-form--horizontal"
                          data-steps="0"
                        >
                          <div className="breakdance-form-field breakdance-form-field--email">
                            <input
                              className="breakdance-form-field__input"
                              id="tickets_email"
                              aria-describedby="tickets_email"
                              type="email"
                              name="fields[tickets_email]"
                              placeholder="username@example.com *"
                              value=""
                              required={true}
                            />
                          </div>
                          <div className="breakdance-form-field breakdance-form-field--hpinput">
                            <label className="breakdance-form-field__label" htmlFor="hpname">
                              HP Name
                            </label>
                            <input
                              className="breakdance-form-field__input"
                              id="hpname"
                              aria-describedby="hpname"
                              type="hpinput"
                              name="fields[hpname]"
                              placeholder=""
                              value=""
                              autoComplete="off"
                              tabIndex="-1"
                            />
                          </div>
                          <div className="breakdance-form-field breakdance-form-footer">
                            <button
                              type="submit"
                              className="button-atom button-atom--primary breakdance-form-button breakdance-form-button__submit"
                            >
                              <span className="button-atom__text">Notify Me!</span>
                            </button>
                            <input type="hidden" name="form_id" value="113" />
                            <input type="hidden" name="post_id" value="85" />
                          </div>
                        </form>
                      </div>{" "}
                      <div className="bde-fancy-divider-85-107 bde-fancy-divider">
                        <div className="bde-fancy-divider__wrapper">
                          <div className="bde-fancy-divider__separator   "></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
            <div
              className="breakdance-popup-close-button breakdance-popup-position-top-right"
              data-breakdance-popup-reference="85"
              data-breakdance-popup-action="close"
            >
              <div className="breakdance-popup-close-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                  <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"></path>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="breakdance">
        <div className="bde-popup-44-100 bde-popup">
          <div
            className="breakdance-popup
    "
            data-breakdance-popup-id="44"
          >
            <div className="breakdance-popup-content">
              <section className="bde-section-44-101 bde-section">
                <div className="section-container">
                  <img
                    className="bde-image2-44-102 bde-image2"
                    src="images/colorcode-events-logo.svg"
                    alt="ColorCode Events"
                    loading="lazy"
                    sizes="(max-width: 1px) 100vw, 1px"
                  />
                </div>
              </section>{" "}
              <section className="bde-section-44-103 bde-section">
                <div className="section-container">
                  <div className="bde-columns-44-104 bde-columns">
                    <div className="bde-column-44-105 bde-column">
                      <h1 className="bde-heading-44-106 bde-heading">Jump to:</h1>{" "}
                      <div id="tickets-info" className="bde-button-44-112 bde-button">
                        <a
                          className="breakdance-link button-atom button-atom--custom bde-button__button"
                          href="#tickets-info"
                          target="_self"
                          data-type="url"
                        >
                          <span className="button-atom__text">Get Tickets!</span>
                        </a>
                      </div>{" "}
                      <div className="bde-fancy-divider-44-107 bde-fancy-divider">
                        <div className="bde-fancy-divider__wrapper">
                          <div className="bde-fancy-divider__separator   "></div>
                        </div>
                      </div>{" "}
                      <div className="bde-rich-text-44-109 bde-rich-text breakdance-rich-text-styles">
                        <p>
                          <a href="/privacy-policy/">Privacy</a> |{" "}
                          <a href="/code-of-conduct/">Code of Conduct</a>
                        </p>
                      </div>
                    </div>{" "}
                    <div className="bde-column-44-110 bde-column">
                      <div className="bde-wp-menu-44-111 bde-wp-menu">
                        <nav className="breakdance-menu breakdance-menu--collapse breakdance-menu--vertical   ">
                          <button
                            className="breakdance-menu-toggle breakdance-menu-toggle--squeeze"
                            type="button"
                            aria-label="Open Menu"
                            aria-expanded="false"
                            aria-controls="menu-111"
                          >
                            <span className="breakdance-menu-toggle-icon">
                              <span className="breakdance-menu-toggle-lines"></span>
                            </span>
                          </button>
                          <ul className="breakdance-menu-list" id="menu-111">
                            <li
                              id="menu-item-53"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-53 breakdance-menu-item"
                            >
                              <a href="https://colorcode.events/" className="breakdance-menu-link">
                                Home
                              </a>
                            </li>
                            <li
                              id="menu-item-622"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-622 breakdance-menu-item"
                            >
                              <a
                                href="https://colorcode.events/call-for-sponsors/"
                                className="breakdance-menu-link"
                              >
                                Call For Sponsors
                              </a>
                            </li>
                            <li
                              id="menu-item-623"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-623 breakdance-menu-item"
                            >
                              <a
                                href="https://colorcode.events/call-for-speakers/"
                                className="breakdance-menu-link"
                              >
                                Call For Speakers
                              </a>
                            </li>
                            <li
                              id="menu-item-55"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-55 breakdance-menu-item breakdance-dropdown breakdance-dropdown--wp breakdance-dropdown--with-link"
                            >
                              <div className="breakdance-dropdown-toggle">
                                <a
                                  href="https://colorcode.events/events/"
                                  className="breakdance-menu-link"
                                  aria-expanded="false"
                                >
                                  Events
                                </a>{" "}
                                <button
                                  className="breakdance-menu-link-arrow"
                                  type="button"
                                  aria-expanded="false"
                                  aria-label="Events Submenu"
                                ></button>
                              </div>{" "}
                              <div className="breakdance-dropdown-floater" aria-hidden="true">
                                <div className="breakdance-dropdown-body">
                                  <div className="breakdance-dropdown-section">
                                    <ul className="breakdance-dropdown-links">
                                      <li
                                        id="menu-item-57"
                                        className="menu-item menu-item-type-post_type menu-item-object-page menu-item-57 breakdance-dropdown-item"
                                      >
                                        <a
                                          href="https://colorcode.events/buffalo/"
                                          className="breakdance-dropdown-link"
                                        >
                                          <span className="breakdance-dropdown-link__text">
                                            Buffalo 2026
                                          </span>
                                        </a>
                                      </li>
                                      <li
                                        id="menu-item-620"
                                        className="menu-item menu-item-type-post_type menu-item-object-page menu-item-620 breakdance-dropdown-item"
                                      >
                                        <a
                                          href="https://colorcode.events/buffalo-2025/"
                                          className="breakdance-dropdown-link"
                                        >
                                          <span className="breakdance-dropdown-link__text">
                                            Buffalo 2025 Archive
                                          </span>
                                        </a>
                                      </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </li>
                            <li
                              id="menu-item-59"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-59 breakdance-menu-item breakdance-dropdown breakdance-dropdown--wp breakdance-dropdown--with-link"
                            >
                              <div className="breakdance-dropdown-toggle">
                                <a
                                  href="https://colorcode.events/about/"
                                  className="breakdance-menu-link"
                                  aria-expanded="false"
                                >
                                  About
                                </a>{" "}
                                <button
                                  className="breakdance-menu-link-arrow"
                                  type="button"
                                  aria-expanded="false"
                                  aria-label="About Submenu"
                                ></button>
                              </div>{" "}
                              <div className="breakdance-dropdown-floater" aria-hidden="true">
                                <div className="breakdance-dropdown-body">
                                  <div className="breakdance-dropdown-section">
                                    <ul className="breakdance-dropdown-links">
                                      <li
                                        id="menu-item-624"
                                        className="menu-item menu-item-type-post_type menu-item-object-page menu-item-624 breakdance-dropdown-item"
                                      >
                                        <a
                                          href="https://colorcode.events/code-of-conduct/"
                                          className="breakdance-dropdown-link"
                                        >
                                          <span className="breakdance-dropdown-link__text">
                                            Code of Conduct
                                          </span>
                                        </a>
                                      </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </li>
                            <li
                              id="menu-item-401"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-401 breakdance-menu-item"
                            >
                              <a
                                href="https://colorcode.events/blog/"
                                className="breakdance-menu-link"
                              >
                                Blog
                              </a>
                            </li>
                            <li
                              id="menu-item-84"
                              className="menu-item menu-item-type-post_type menu-item-object-page menu-item-84 breakdance-menu-item"
                            >
                              <a
                                href="https://colorcode.events/contact/"
                                className="breakdance-menu-link"
                              >
                                Contact
                              </a>
                            </li>
                          </ul>
                        </nav>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
            <div
              className="breakdance-popup-close-button breakdance-popup-position-top-right"
              data-breakdance-popup-reference="44"
              data-breakdance-popup-action="close"
            >
              <div className="breakdance-popup-close-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                  <path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"></path>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
