interface BlogPostPageProps {
  [key: string]: unknown;
}

export function CorvusBlogPostPage(props: BlogPostPageProps) {
  void props;
  return (
    <main className="page-blog-post">
      {/* corvus blog-post layout — stub, to be regenerated by pipeline */}
    </main>
  );
}
