/* eslint-disable */
// @ts-nocheck
// Auto-generated by extract-theme --pass componentize
// This is a clone-fidelity component — not a production template.
// Run extract-theme --pass strip to replace content with props.

interface BlogPostPageProps {
  [key: string]: unknown;
}

export function CorvusBlogPostPage(props: BlogPostPageProps) {
  void props;
  return (
    <>
      {/* header extracted to component */}
      <section className="bde-section-171-100 bde-section">
        <div className="section-container">
          <div className="bde-div-171-101 bde-div">
            <div className="bde-columns-171-102 bde-columns">
              <div className="bde-column-171-103 bde-column">
                <h2 className="bde-heading-171-104 bde-heading">
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span>{" "}
                  <span className="graphic yellow_slash"></span> Blog
                </h2>
              </div>
            </div>
          </div>{" "}
          <div className="bde-div-171-105 bde-div">
            <div className="bde-columns-171-106 bde-columns">
              <div className="bde-column-171-107 bde-column">
                <h1 className="bde-heading-171-109 bde-heading">{props.heading}</h1>{" "}
                <div className="bde-text-171-110 bde-text">April 28, 2025</div>{" "}
                <div className="bde-rich-text-171-111 bde-rich-text breakdance-rich-text-styles">
                  <p>{props.body}</p>
                  <p>{props.description}</p>
                  <p>{props.bodyText}</p>
                  <p>{props.paragraph}</p>
                  <ol>
                    <li>Expand event topics beyond WordPress specific topics</li>
                    <li>
                      Brand the event and build assets exactly how we wanted without trademark or
                      platform restrictions
                    </li>
                    <li>Build sponsorship relationships directly rather than being handed them</li>
                    <li>
                      Run the planning and logistics of the event and promotional marketing the way
                      we wanted to
                    </li>
                  </ol>
                  <p>{props.body5}</p>
                  <p>{props.body6}</p>
                  <p>{props.body7}</p>
                  <p>{props.body8}</p>
                  <p>{props.body9}</p>
                  <p>Thanks for coming along for the ride!</p>
                  <p>&#8211; Tim</p>
                </div>{" "}
                <a
                  className="bde-text-link-171-112 bde-text-link breakdance-link"
                  href="/blog/"
                  target="_self"
                  data-type="url"
                >
                  « Back To Blog
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bde-section-40-100 bde-section">
        <div className="section-container">
          <div className="bde-div-40-101 bde-div">
            <div className="bde-div-40-102 bde-div">
              <h4 className="bde-heading-40-103 bde-heading">{props.sectionTitle}</h4>{" "}
              <div className="bde-text-40-104 bde-text">
                The latest event news, articles, and resources, sent to your inbox.
              </div>
            </div>{" "}
            <div className="bde-form-builder-40-105 bde-form-builder">
              <form
                id="contact-form105"
                className="breakdance-form breakdance-form--horizontal"
                data-steps="0"
              >
                <div className="breakdance-form-field breakdance-form-field--email breakdance-form-field__hide-label">
                  <input
                    className="breakdance-form-field__input"
                    id="newsletter_email"
                    aria-describedby="newsletter_email"
                    type="email"
                    name="fields[newsletter_email]"
                    placeholder="{props.email} *"
                    value=""
                    required={true}
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-field--hpinput">
                  <label className="breakdance-form-field__label" htmlFor="hpname">
                    HP Name
                  </label>
                  <input
                    className="breakdance-form-field__input"
                    id="hpname"
                    aria-describedby="hpname"
                    type="hpinput"
                    name="fields[hpname]"
                    placeholder=""
                    value=""
                    autoComplete="off"
                    tabIndex="-1"
                  />
                </div>
                <div className="breakdance-form-field breakdance-form-footer">
                  <button
                    type="submit"
                    className="button-atom button-atom--primary breakdance-form-button breakdance-form-button__submit"
                  >
                    <span className="button-atom__text">Submit</span>
                  </button>
                  <input type="hidden" name="form_id" value="105" />
                  <input type="hidden" name="post_id" value="40" />
                </div>
              </form>
            </div>
          </div>{" "}
          <div className="bde-columns-40-106 bde-columns">
            <div className="bde-column-40-107 bde-column">
              <div className="bde-text-40-108 bde-text">Events</div>{" "}
              <a
                className="bde-text-link-40-109 bde-text-link breakdance-link"
                href="/buffalo/"
                target="_self"
                data-type="url"
              >
                ColorCode Buffalo
              </a>
            </div>{" "}
            <div className="bde-column-40-110 bde-column">
              <div className="bde-text-40-111 bde-text">Support</div>{" "}
              <a
                className="bde-text-link-40-112 bde-text-link breakdance-link"
                href="/call-for-sponsors/"
                target="_self"
                data-type="url"
              >
                Call For Sponsors
              </a>{" "}
              <a
                className="bde-text-link-40-130 bde-text-link breakdance-link"
                href="/call-for-speakers/"
                target="_self"
                data-type="url"
              >
                Call For Speakers
              </a>{" "}
              <a
                className="bde-text-link-40-113 bde-text-link breakdance-link"
                href="/call-for-volunteers/"
                target="_self"
                data-type="url"
              >
                Call For Volunteers
              </a>
            </div>{" "}
            <div className="bde-column-40-114 bde-column">
              <div className="bde-text-40-115 bde-text">Legal</div>{" "}
              <a
                className="bde-text-link-40-116 bde-text-link breakdance-link"
                href="/code-of-conduct/"
                target="_self"
                data-type="url"
              >
                Code of Conduct
              </a>{" "}
              <a
                className="bde-text-link-40-117 bde-text-link breakdance-link"
                href="/privacy-policy/"
                target="_self"
                data-type="url"
              >
                Privacy
              </a>
            </div>{" "}
            <div className="bde-column-40-119 bde-column">
              <div className="bde-text-40-120 bde-text">Company</div>{" "}
              <a
                className="bde-text-link-40-121 bde-text-link breakdance-link"
                href="/about/"
                target="_self"
                data-type="url"
              >
                About
              </a>{" "}
              <a
                className="bde-text-link-40-129 bde-text-link breakdance-link"
                href="/contact/"
                target="_self"
                data-type="url"
              >
                Contact
              </a>
            </div>{" "}
            <div className="bde-column-40-123 bde-column">
              <img
                className="bde-image2-40-124 bde-image2"
                src={props.imageSrc}
                alt="ColorCode Events"
                loading="lazy"
                sizes="(max-width: 1px) 100vw, 1px"
              />
            </div>
          </div>{" "}
          <div className="bde-fancy-divider-40-125 bde-fancy-divider">
            <div className="bde-fancy-divider__wrapper">
              <div className="bde-fancy-divider__separator   "></div>
            </div>
          </div>{" "}
          <div className="bde-div-40-126 bde-div">
            <p className="de-cry-40-127 de-cry">{props.body10}</p>{" "}
            <div className="bde-social-icons-40-128 bde-social-icons">
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-facebook"
                href={props.facebookUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="facebook"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-instagram"
                href={props.instagramUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="instagram"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-twitter"
                href={props.xUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="twitter"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 512 512">
                  <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                </svg>
              </a>
              <a
                className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-linkedin"
                href={props.linkedinUrl ?? "#"}
                target="_blank"
                data-type="url"
                aria-label="linkedin"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="-4 -2 32 32">
                  <path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
