interface CustomPageProps {
  [key: string]: unknown;
}

export function CorvusCustomPage(props: CustomPageProps) {
  void props;
  return (
    <main className="page-custom">
      {/* corvus custom layout — stub, to be regenerated by pipeline */}
    </main>
  );
}
