interface HomePageProps {
  [key: string]: unknown;
}

export function CorvusHomePage(props: HomePageProps) {
  void props;
  return (
    <main className="page-home">
      {/* corvus home layout — stub, to be regenerated by pipeline */}
    </main>
  );
}
