/* eslint-disable */
// @ts-nocheck
// Auto-generated by extract-theme --pass componentize
// This is a clone-fidelity component — not a production template.
// Run extract-theme --pass strip to replace content with props.

interface HomePageProps {
  [key: string]: unknown;
}

export function CorvusHomePage(props: HomePageProps) {
  void props;
  return (
    <>
      {/* header extracted to component */}
      <section className="bde-section-17-100 bde-section">
        <div className="section-container">
          <div className="bde-code-block-17-463 bde-code-block">
            <div className="callout">
              A Fresh <span className="graphic yellow_rectangle"></span>Digital <br />
              <span className="graphic red_slash"></span>{" "}
              <span className="graphic red_slash"></span>{" "}
              <span className="graphic red_slash"></span>{" "}
              <span className="graphic red_slash"></span>Conference <br />
              for C <span className="graphic green_circle"></span>ol Pe{" "}
              <span className="graphic green_circle"></span>ple <br />
              Doing <span className="graphic right_triangle blue_border"></span>{" "}
              <span className="graphic right_triangle orange_border"></span>{" "}
              <span className="graphic right_triangle orange_border"></span>Cool <br />
              Things. <span className="bullet purple long"></span>{" "}
              <span className="bullet blue short"></span>
            </div>
          </div>
          <section className="bde-section-17-103 bde-section">
            <div className="section-background-overlay"></div>
            <div className="section-container">
              <div className="bde-columns-17-104 bde-columns">
                <div className="bde-column-17-105 bde-column">
                  <img
                    className="bde-image2-17-107 bde-image2"
                    src={props.imageSrc}
                    alt="ColorCode: Buffalo"
                    loading="lazy"
                    sizes="(max-width: 1px) 100vw, 1px"
                  />
                </div>{" "}
                <div className="bde-column-17-106 bde-column">
                  <div className="bde-div-17-111 bde-div">
                    <h3 className="bde-heading-17-108 bde-heading">{props.sectionTitle5}</h3>{" "}
                    <h3 className="bde-heading-17-109 bde-heading">{props.sectionTitle6}</h3>{" "}
                    <h3 className="bde-heading-17-112 bde-heading">{props.sectionTitle7}</h3>{" "}
                    <h3 className="bde-heading-17-110 bde-heading">{props.sectionTitle8}</h3>{" "}
                    <div className="bde-div-17-712 bde-div">
                      <div className="bde-button-17-113 bde-button bde-preset-337602b3-5cf2-4cf7-883f-6d7491bb1230">
                        <a
                          className="breakdance-link button-atom button-atom--custom bde-button__button"
                          href="/buffalo/"
                          target="_self"
                          data-type="url"
                        >
                          <span className="button-atom__text">Event Info</span>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>{" "}
          <section className="bde-section-17-114 bde-section">
            <div className="section-container">
              <div className="bde-div-17-115 bde-div">
                <div className="bde-columns-17-117 bde-columns">
                  <div className="bde-column-17-118 bde-column">
                    <h2 className="bde-heading-17-661 bde-heading">{props.sectionTitle}</h2>{" "}
                    <div className="bde-text-17-121 bde-text">
                      Are you a passionate designer, developer, writer, or marketer dying to share
                      your hot takes on what's next or best practices? We are actively seeking a
                      wide variety of topics and a diverse speaker pool for ColorCode Buffalo on
                      July 25th, 2026.
                    </div>{" "}
                    <div className="bde-button-17-122 bde-button bde-preset-e1b6219c-3d35-4d9e-89f3-51677ed65931">
                      <a
                        className="breakdance-link button-atom button-atom--custom bde-button__button"
                        href="/call-for-speakers/"
                        target="_self"
                        data-type="url"
                      >
                        <span className="button-atom__text">Apply To Speak</span>
                      </a>
                    </div>
                  </div>{" "}
                  <div className="bde-column-17-123 bde-column">
                    <div className="bde-div-17-127 bde-div">
                      <div className="bde-image-17-124 bde-image" data-entrance="slideLeft">
                        <figure className="breakdance-image breakdance-image--24">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.heroImageSrc}
                                width="200"
                                height="200"
                                srcSet="images/shape-green-half-circle.png 200w, images/shape-green-half-circle-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-128 bde-image" data-entrance="slideRight">
                        <figure className="breakdance-image breakdance-image--26">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.cardImageSrc}
                                width="200"
                                height="200"
                                srcSet="images/shape-orange-arrow.png 200w, images/shape-orange-arrow-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-129 bde-image" data-entrance="slideUp">
                        <figure className="breakdance-image breakdance-image--25">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.sectionImageSrc}
                                width="200"
                                height="200"
                                srcSet="images/shape-magenta-slashes.png 200w, images/shape-magenta-slashes-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-125 bde-image" data-entrance="slideUp">
                        <figure className="breakdance-image breakdance-image--627">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.imageSrc5}
                                width="1000"
                                height="1000"
                                srcSet="images/CCE_Speaker-1_1000x1000.png 1000w, images/CCE_Speaker-1_1000x1000-300x300.png 300w, images/CCE_Speaker-1_1000x1000-150x150.png 150w, images/CCE_Speaker-1_1000x1000-768x768.png 768w"
                                sizes="(max-width: 1000px) 100vw, 1000px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>
                    </div>
                  </div>
                </div>
              </div>{" "}
              <div className="bde-div-17-130 bde-div">
                <div className="bde-columns-17-131 bde-columns">
                  <div className="bde-column-17-136 bde-column">
                    <div className="bde-div-17-137 bde-div">
                      <div className="bde-image-17-138 bde-image" data-entrance="slideLeft">
                        <figure className="breakdance-image breakdance-image--28">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.imageSrc6}
                                width="200"
                                height="200"
                                srcSet="images/shape-green-arrow.png 200w, images/shape-green-arrow-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-139 bde-image" data-entrance="slideRight">
                        <figure className="breakdance-image breakdance-image--29">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.imageSrc7}
                                width="200"
                                height="200"
                                srcSet="images/shape-yellow-box.png 200w, images/shape-yellow-box-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-140 bde-image" data-entrance="slideUp">
                        <figure className="breakdance-image breakdance-image--30">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.imageSrc8}
                                width="200"
                                height="200"
                                srcSet="images/shape-magenta-circle.png 200w, images/shape-magenta-circle-150x150.png 150w"
                                sizes="(max-width: 200px) 100vw, 200px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>{" "}
                      <div className="bde-image-17-141 bde-image" data-entrance="slideUp">
                        <figure className="breakdance-image breakdance-image--629">
                          <div className="breakdance-image-container">
                            <div className="breakdance-image-clip">
                              <img
                                className="breakdance-image-object"
                                src={props.imageSrc9}
                                width="1000"
                                height="1000"
                                srcSet="images/CCE_Sponsor-1_1000x1000.png 1000w, images/CCE_Sponsor-1_1000x1000-300x300.png 300w, images/CCE_Sponsor-1_1000x1000-150x150.png 150w, images/CCE_Sponsor-1_1000x1000-768x768.png 768w"
                                sizes="(max-width: 1000px) 100vw, 1000px"
                              />
                            </div>
                          </div>
                        </figure>
                      </div>
                    </div>
                  </div>{" "}
                  <div className="bde-column-17-132 bde-column">
                    <h2 className="bde-heading-17-660 bde-heading">{props.sectionTitle2}</h2>{" "}
                    <div className="bde-text-17-134 bde-text">
                      With crowds of designers, bloggers, developers, users, educators and more,
                      sponsors help support an event aimed to spread knowledge and inspiration to
                      all who attend.
                    </div>{" "}
                    <div className="bde-button-17-135 bde-button bde-preset-f39415e4-d4ba-43a0-ad34-0fa62a416fdd">
                      <a
                        className="breakdance-link button-atom button-atom--custom bde-button__button"
                        href="/call-for-sponsors/#sponsor-levels"
                        target="_self"
                        data-type="url"
                      >
                        <span className="button-atom__text">View Sponsor Levels</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>{" "}
              <div className="bde-div-17-717 bde-div">
                <div className="bde-columns-17-718 bde-columns">
                  <div className="bde-column-17-725 bde-column">
                    <h2 className="bde-heading-17-726 bde-heading">{props.sectionTitle3}</h2>{" "}
                    <div className="bde-text-17-727 bde-text">
                      With crowds of designers, bloggers, developers, users, educators and more,
                      sponsors help support an event aimed to spread knowledge and inspiration to
                      all who attend.
                    </div>{" "}
                    <div className="bde-button-17-728 bde-button bde-preset-337602b3-5cf2-4cf7-883f-6d7491bb1230">
                      <a
                        className="breakdance-link button-atom button-atom--custom bde-button__button"
                        href="/call-for-volunteers/"
                        target="_self"
                        data-type="url"
                      >
                        <span className="button-atom__text">Apply to Volunteer</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>{" "}
              <div className="bde-div-17-729 bde-div">
                <div className="bde-columns-17-730 bde-columns">
                  <div className="bde-column-17-731 bde-column">
                    <h2 className="bde-heading-17-733 bde-heading">{props.sectionTitle4}</h2>{" "}
                    <div className="bde-post-list-17-732 bde-post-list">
                      <div className="bde-loop bde-loop-grid ee-posts ee-posts-grid">
                        <article className="bde-loop-item ee-post">
                          <a
                            className="bde-loop-item__image-link ee-post-image-link "
                            href="/blog/the-journey-to-our-first-colorcode-buffalo/"
                            aria-label="The Journey to Our First ColorCode: Buffalo"
                          >
                            <div className="bde-loop-item__image ee-post-image">
                              <img
                                width="1150"
                                height="680"
                                src={props.imageSrc10}
                                className="attachment-full size-full wp-post-image"
                                alt=""
                                decoding="async"
                                loading="lazy"
                                srcSet="images/colorcode-buffalo-share.jpg 1150w, images/colorcode-buffalo-share-300x177.jpg 300w, images/colorcode-buffalo-share-1024x605.jpg 1024w, images/colorcode-buffalo-share-768x454.jpg 768w"
                                sizes="auto, (max-width: 1150px) 100vw, 1150px"
                              />
                            </div>
                          </a>
                          <div className="bde-loop-item__wrap ee-post-wrap">
                            <h3 className="ee-post-title">
                              <a
                                className="bde-loop-item__title-link ee-post-title-link"
                                href="/blog/the-journey-to-our-first-colorcode-buffalo/"
                              >
                                The Journey to Our First ColorCode: Buffalo
                              </a>
                            </h3>
                            <div className="bde-loop-item__post-meta ee-post-meta">
                              <span className="bde-loop-item__meta-date bde-loop-item__meta-item ee-post-meta-date ee-post-meta-item">
                                April 28, 2025
                              </span>
                            </div>
                            <div className="bde-loop-item__content ee-post-content">
                              It&#8217;s crazy to think about the last year in the design, web dev,
                              WordPress, and even marketing world in general. Between #WPDrama and
                              AI taking over along with the stubborn&hellip;
                            </div>
                            <a
                              className="breakdance-link button-atom button-atom--primary bde-loop-item__button ee-post-button"
                              href="/blog/the-journey-to-our-first-colorcode-buffalo/"
                              target="_self"
                              data-type=""
                            >
                              <span className="button-atom__text">Read more</span>
                            </a>
                          </div>
                        </article>
                        <article className="bde-loop-item ee-post">
                          <a
                            className="bde-loop-item__image-link ee-post-image-link "
                            href="/blog/announcing-the-colorcode-art-battle/"
                            aria-label="Announcing the ColorCode Art Battle"
                          >
                            <div className="bde-loop-item__image ee-post-image">
                              <img
                                width="2560"
                                height="1598"
                                src={props.imageSrc11}
                                className="attachment-full size-full wp-post-image"
                                alt=""
                                decoding="async"
                                loading="lazy"
                                srcSet="images/Untitled_Artwork-2-scaled.jpg 2560w, images/Untitled_Artwork-2-300x187.jpg 300w, images/Untitled_Artwork-2-1024x639.jpg 1024w, images/Untitled_Artwork-2-768x479.jpg 768w, images/Untitled_Artwork-2-1536x959.jpg 1536w, images/Untitled_Artwork-2-2048x1279.jpg 2048w"
                                sizes="auto, (max-width: 2560px) 100vw, 2560px"
                              />
                            </div>
                          </a>
                          <div className="bde-loop-item__wrap ee-post-wrap">
                            <h3 className="ee-post-title">
                              <a
                                className="bde-loop-item__title-link ee-post-title-link"
                                href="/blog/announcing-the-colorcode-art-battle/"
                              >
                                Announcing the ColorCode Art Battle
                              </a>
                            </h3>
                            <div className="bde-loop-item__post-meta ee-post-meta">
                              <span className="bde-loop-item__meta-date bde-loop-item__meta-item ee-post-meta-date ee-post-meta-item">
                                March 31, 2025
                              </span>
                            </div>
                            <div className="bde-loop-item__content ee-post-content">
                              As part of our inaugural event, we&#8217;ll be staging our first Art
                              Battle! All attendees are welcome to participate. Here&#8217;s how it
                              works: Several easels holding large post-it pads will&hellip;
                            </div>
                            <a
                              className="breakdance-link button-atom button-atom--primary bde-loop-item__button ee-post-button"
                              href="/blog/announcing-the-colorcode-art-battle/"
                              target="_self"
                              data-type=""
                            >
                              <span className="button-atom__text">Read more</span>
                            </a>
                          </div>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>{" "}
          <section className="bde-section-17-142 bde-section">
            <div className="section-container">
              <div className="bde-columns-17-143 bde-columns">
                <div className="bde-column-17-144 bde-column">
                  <h1 className="bde-heading-17-713 bde-heading">{props.heading}</h1>
                </div>{" "}
                <div className="bde-column-17-145 bde-column"></div>
              </div>{" "}
              <div className="bde-columns-17-147 bde-columns">
                <div className="bde-column-17-148 bde-column">
                  <img
                    className="bde-image2-17-151 bde-image2"
                    src={props.imageSrc12}
                    loading="lazy"
                    srcSet="images/row-magenta-arrows.png 590w, images/row-magenta-arrows-300x33.png 300w"
                    sizes="(max-width: 590px) 100vw, 590px"
                    data-entrance="slideLeft"
                  />
                </div>{" "}
                <div className="bde-column-17-150 bde-column">
                  <div className="bde-rich-text-17-152 bde-rich-text breakdance-rich-text-styles">
                    <p>{props.body}</p>
                  </div>{" "}
                  <div className="bde-button-17-716 bde-button bde-preset-337602b3-5cf2-4cf7-883f-6d7491bb1230">
                    <a
                      className="breakdance-link button-atom button-atom--custom bde-button__button"
                      href="/about/"
                      target="_self"
                      data-type="url"
                    >
                      <span className="button-atom__text">Learn More</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </section>{" "}
          <section className="bde-section-17-714 bde-section">
            <div className="section-container">
              <div className="bde-gallery-17-715 bde-gallery">
                <div className="ee-gallery-swiper breakdance-swiper-wrapper" data-swiper-id="715">
                  <div className="swiper">
                    <div className="ee-gallery ee-gallery--gallery-slider ee-gallery--slider ee-gallery--single ee-gallery-- ee-gallery-- ee-gallery--caption- ee-gallery--caption-none ee-gallery--ratio swiper-wrapper">
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-social-5.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="1333-2000"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc13}
                            width="768"
                            height="1152"
                            srcSet="images/color-code-buffalo-2025-social-5.jpg 1333w, images/color-code-buffalo-2025-social-5-200x300.jpg 200w, images/color-code-buffalo-2025-social-5-682x1024.jpg 682w, images/color-code-buffalo-2025-social-5-768x1152.jpg 768w, images/color-code-buffalo-2025-social-5-1024x1536.jpg 1024w"
                            sizes="(max-width: 1333px) 100vw, 1333px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-lewis.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc14}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-lewis.jpg 2000w, images/color-code-buffalo-2025-lewis-300x200.jpg 300w, images/color-code-buffalo-2025-lewis-1024x682.jpg 1024w, images/color-code-buffalo-2025-lewis-768x512.jpg 768w, images/color-code-buffalo-2025-lewis-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-social-4.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc15}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-social-4.jpg 2000w, images/color-code-buffalo-2025-social-4-300x200.jpg 300w, images/color-code-buffalo-2025-social-4-1024x682.jpg 1024w, images/color-code-buffalo-2025-social-4-768x512.jpg 768w, images/color-code-buffalo-2025-social-4-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-cleary.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc16}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-cleary.jpg 2000w, images/color-code-buffalo-2025-cleary-300x200.jpg 300w, images/color-code-buffalo-2025-cleary-1024x682.jpg 1024w, images/color-code-buffalo-2025-cleary-768x512.jpg 768w, images/color-code-buffalo-2025-cleary-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-social-3.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc17}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-social-3.jpg 2000w, images/color-code-buffalo-2025-social-3-300x200.jpg 300w, images/color-code-buffalo-2025-social-3-1024x682.jpg 1024w, images/color-code-buffalo-2025-social-3-768x512.jpg 768w, images/color-code-buffalo-2025-social-3-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/event-sponsor-luminus.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-2000"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc18}
                            width="768"
                            height="768"
                            srcSet="images/event-sponsor-luminus.jpg 2000w, images/event-sponsor-luminus-300x300.jpg 300w, images/event-sponsor-luminus-1024x1024.jpg 1024w, images/event-sponsor-luminus-150x150.jpg 150w, images/event-sponsor-luminus-768x768.jpg 768w, images/event-sponsor-luminus-1536x1536.jpg 1536w, images/event-sponsor-luminus-400x400.jpg 400w, images/event-sponsor-luminus-600x600.jpg 600w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-reimann.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc19}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-reimann.jpg 2000w, images/color-code-buffalo-2025-reimann-300x200.jpg 300w, images/color-code-buffalo-2025-reimann-1024x682.jpg 1024w, images/color-code-buffalo-2025-reimann-768x512.jpg 768w, images/color-code-buffalo-2025-reimann-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div
                        className="ee-gallery-item ee-gallery-item--image ee-gallery-item--single swiper-slide"
                        href="images/color-code-buffalo-2025-bolling.jpg"
                        data-sub-html="<span></span>"
                        data-category="1"
                        data-lg-size="2000-1333"
                      >
                        <figure className="ee-gallery-item-figure">
                          <img
                            className="breakdance-image-object"
                            src={props.imageSrc20}
                            width="768"
                            height="512"
                            srcSet="images/color-code-buffalo-2025-bolling.jpg 2000w, images/color-code-buffalo-2025-bolling-300x200.jpg 300w, images/color-code-buffalo-2025-bolling-1024x682.jpg 1024w, images/color-code-buffalo-2025-bolling-768x512.jpg 768w, images/color-code-buffalo-2025-bolling-1536x1024.jpg 1536w"
                            sizes="(max-width: 2000px) 100vw, 2000px"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                    </div>
                  </div>
                  <div className="swiper-button-prev"></div>
                  <div className="swiper-button-next"></div>
                </div>
              </div>
            </div>
          </section>{" "}
          <section className="bde-section-40-100 bde-section">
            <div className="section-container">
              <div className="bde-div-40-101 bde-div">
                <div className="bde-div-40-102 bde-div">
                  <h4 className="bde-heading-40-103 bde-heading">{props.sectionTitle9}</h4>{" "}
                  <div className="bde-text-40-104 bde-text">
                    The latest event news, articles, and resources, sent to your inbox.
                  </div>
                </div>{" "}
                <div className="bde-form-builder-40-105 bde-form-builder">
                  <form
                    id="contact-form105"
                    className="breakdance-form breakdance-form--horizontal"
                    data-steps="0"
                  >
                    <div className="breakdance-form-field breakdance-form-field--email breakdance-form-field__hide-label">
                      <input
                        className="breakdance-form-field__input"
                        id="newsletter_email"
                        aria-describedby="newsletter_email"
                        type="email"
                        name="fields[newsletter_email]"
                        placeholder="{props.email} *"
                        value=""
                        required={true}
                      />
                    </div>
                    <div className="breakdance-form-field breakdance-form-field--hpinput">
                      <label className="breakdance-form-field__label" htmlFor="hpname">
                        HP Name
                      </label>
                      <input
                        className="breakdance-form-field__input"
                        id="hpname"
                        aria-describedby="hpname"
                        type="hpinput"
                        name="fields[hpname]"
                        placeholder=""
                        value=""
                        autoComplete="off"
                        tabIndex="-1"
                      />
                    </div>
                    <div className="breakdance-form-field breakdance-form-footer">
                      <button
                        type="submit"
                        className="button-atom button-atom--primary breakdance-form-button breakdance-form-button__submit"
                      >
                        <span className="button-atom__text">Submit</span>
                      </button>
                      <input type="hidden" name="form_id" value="105" />
                      <input type="hidden" name="post_id" value="40" />
                    </div>
                  </form>
                </div>
              </div>{" "}
              <div className="bde-columns-40-106 bde-columns">
                <div className="bde-column-40-107 bde-column">
                  <div className="bde-text-40-108 bde-text">Events</div>{" "}
                  <a
                    className="bde-text-link-40-109 bde-text-link breakdance-link"
                    href="/buffalo/"
                    target="_self"
                    data-type="url"
                  >
                    ColorCode Buffalo
                  </a>
                </div>{" "}
                <div className="bde-column-40-110 bde-column">
                  <div className="bde-text-40-111 bde-text">Support</div>{" "}
                  <a
                    className="bde-text-link-40-112 bde-text-link breakdance-link"
                    href="/call-for-sponsors/"
                    target="_self"
                    data-type="url"
                  >
                    Call For Sponsors
                  </a>{" "}
                  <a
                    className="bde-text-link-40-130 bde-text-link breakdance-link"
                    href="/call-for-speakers/"
                    target="_self"
                    data-type="url"
                  >
                    Call For Speakers
                  </a>{" "}
                  <a
                    className="bde-text-link-40-113 bde-text-link breakdance-link"
                    href="/call-for-volunteers/"
                    target="_self"
                    data-type="url"
                  >
                    Call For Volunteers
                  </a>
                </div>{" "}
                <div className="bde-column-40-114 bde-column">
                  <div className="bde-text-40-115 bde-text">Legal</div>{" "}
                  <a
                    className="bde-text-link-40-116 bde-text-link breakdance-link"
                    href="/code-of-conduct/"
                    target="_self"
                    data-type="url"
                  >
                    Code of Conduct
                  </a>{" "}
                  <a
                    className="bde-text-link-40-117 bde-text-link breakdance-link"
                    href="/privacy-policy/"
                    target="_self"
                    data-type="url"
                  >
                    Privacy
                  </a>
                </div>{" "}
                <div className="bde-column-40-119 bde-column">
                  <div className="bde-text-40-120 bde-text">Company</div>{" "}
                  <a
                    className="bde-text-link-40-121 bde-text-link breakdance-link"
                    href="/about/"
                    target="_self"
                    data-type="url"
                  >
                    About
                  </a>{" "}
                  <a
                    className="bde-text-link-40-129 bde-text-link breakdance-link"
                    href="/contact/"
                    target="_self"
                    data-type="url"
                  >
                    Contact
                  </a>
                </div>{" "}
                <div className="bde-column-40-123 bde-column">
                  <img
                    className="bde-image2-40-124 bde-image2"
                    src={props.imageSrc21}
                    alt="ColorCode Events"
                    loading="lazy"
                    sizes="(max-width: 1px) 100vw, 1px"
                  />
                </div>
              </div>{" "}
              <div className="bde-fancy-divider-40-125 bde-fancy-divider">
                <div className="bde-fancy-divider__wrapper">
                  <div className="bde-fancy-divider__separator   "></div>
                </div>
              </div>{" "}
              <div className="bde-div-40-126 bde-div">
                <p className="de-cry-40-127 de-cry">{props.description}</p>{" "}
                <div className="bde-social-icons-40-128 bde-social-icons">
                  <a
                    className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-facebook"
                    href={props.facebookUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                    aria-label="facebook"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                      <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                    </svg>
                  </a>
                  <a
                    className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-instagram"
                    href={props.instagramUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                    aria-label="instagram"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 24 24">
                      <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path>
                    </svg>
                  </a>
                  <a
                    className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-twitter"
                    href={props.xUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                    aria-label="twitter"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 512 512">
                      <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                    </svg>
                  </a>
                  <a
                    className="breakdance-link bde-social-icons__icon-wrapper bde-social-icons__icon-linkedin"
                    href={props.linkedinUrl ?? "#"}
                    target="_blank"
                    data-type="url"
                    aria-label="linkedin"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="-4 -2 32 32">
                      <path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </section>
        </div>
      </section>
    </>
  );
}
