import type { DeepPartialThemeConfig } from '@platform/theme-system';
import { atlasRegistry, atlasDefaultConfig } from '@platform/themes/atlas';

/**
 * Test site theme configuration
 * Generated by /pipeline.ingest
 */
export const themeConfig: DeepPartialThemeConfig = {
  componentRegistry: atlasRegistry,
  ...atlasDefaultConfig,
};
