/**
 * Nova Theme
 *
 * Generated by /pipeline.stitch-design
 * Stitch project: Nova Print and Signage Website (id: 5219208513225791321)
 * Trade type: print and signage company
 *
 * Light header, full-bleed image-overlay hero, overlay service cards,
 * dark-accent testimonials and footer sections.
 * Bold orange + green palette — high-impact industrial creative brand.
 *
 * Sites using Nova: (none yet)
 */

import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const novaRegistry: ComponentRegistry = {
  theme: "nova",
  heroVariant: "image-overlay",
  headerVariant: "light",
  cardVariant: "overlay",
  sectionVariant: "dark-accent",
};

export const novaDefaultConfig: DeepPartialThemeConfig = {
  colors: {
    brand: {
      primary: '#e85118',
      primaryHover: '#cc4715',
      secondary: '#5ba829',
      accent: '#1a1a1a',
      onPrimary: '#ffffff',
    },
    surface: {
      background: '#ffffff',
      foreground: '#1a1a1a',
      card: '#ffffff',
      cardBorder: '#d1d5db',
      muted: '#fafafa',
    },
    semantic: {
      success: '#10b981',
      warning: '#f59e0b',
      error: '#b91c1c',
      info: '#3b82f6',
    },
    overlay: {
      dark: 'rgba(0,0,0,0.8)',
      light: 'rgba(255,255,255,0.8)',
      primary: 'rgba(232,81,24,0.8)',
    },
  },
};

registerTheme({ name: 'nova', label: 'Nova', config: novaDefaultConfig });
