#!/usr/bin/env tsx
/**
 * Extract Theme CLI
 *
 * Reads a validated CPF clone directory and produces a theme package.
 *
 * Usage:
 *   npx tsx tools/extract-theme.ts --clone corvus
 *   npx tsx tools/extract-theme.ts --clone corvus --pass translate
 *   npx tsx tools/extract-theme.ts --clone corvus --pass strip
 *   npx tsx tools/extract-theme.ts --brief output/briefs/abc123.json
 */

import * as fs from "fs";
import * as path from "path";

import { JobBriefSchema, type JobBrief } from "./lib/pipeline-brief-types";
import { stripContent } from "./lib/content-stripper";

// ── Argument parsing ─────────────────────────────────────────────────────────

function parseArgs(): { clone?: string; brief?: string; pass?: string; verify?: boolean } {
  const args = process.argv.slice(2);
  const result: { clone?: string; brief?: string; pass?: string; verify?: boolean } = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--clone" && args[i + 1]) result.clone = args[++i];
    else if (args[i] === "--brief" && args[i + 1]) result.brief = args[++i];
    else if (args[i] === "--pass" && args[i + 1]) result.pass = args[++i];
    else if (args[i] === "--verify") result.verify = true;
  }
  return result;
}

// ── Brief auto-discovery ──────────────────────────────────────────────────────

function discoverBrief(cloneName: string): JobBrief | null {
  const briefsDir = path.resolve(__dirname, "..", "output", "briefs");
  if (!fs.existsSync(briefsDir)) return null;

  for (const file of fs.readdirSync(briefsDir)) {
    if (!file.endsWith(".json")) continue;
    try {
      const raw = JSON.parse(fs.readFileSync(path.join(briefsDir, file), "utf-8")) as unknown;
      const brief = JobBriefSchema.parse(raw);
      if (brief.theme?.name === cloneName) {
        console.log(`[extract] Auto-discovered brief: output/briefs/${file}`);
        return brief;
      }
    } catch {
      // Skip invalid briefs
    }
  }
  return null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function toPascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function generateIndexTs(themeName: string): string {
  const pascal = toPascalCase(themeName);
  return `/**
 * ${pascal} Theme
 * Auto-generated by extract-theme pipeline
 */

import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const ${themeName}Registry: ComponentRegistry = {
  theme: "${themeName}",
  heroVariant: "image-overlay",
  headerVariant: "dark",
  cardVariant: "standard",
  sectionVariant: "standard",
};

export const ${themeName}DefaultConfig: DeepPartialThemeConfig = {
  componentRegistry: ${themeName}Registry,
};

registerTheme({
  name: "${themeName}",
  label: "${pascal}",
  config: ${themeName}DefaultConfig,
});
`;
}

function generatePackageJson(themeName: string): object {
  return {
    name: `@platform/themes/${themeName}`,
    version: "0.1.0",
    private: true,
    main: "./index.ts",
    peerDependencies: {
      react: "^18.0.0",
      "react-dom": "^18.0.0",
      next: "^15.0.0",
    },
  };
}

// ── Component generation (stub pass) ─────────────────────────────────────────

function generateComponentsBarrel(themeName: string): string {
  const pascal = toPascalCase(themeName);
  return `export { ${pascal}Header } from './header';
export { ${pascal}Footer } from './footer';
`;
}

function generatePagesBarrel(pageNames: string[]): string {
  if (pageNames.length === 0) return "// No page layouts extracted\n";
  return pageNames.map((n) => `export * from "./${n}";`).join("\n") + "\n";
}

/**
 * Generate a stub page component file for a named export that doesn't yet
 * have a real implementation extracted from the clone.
 */
function generateStubPage(exportName: string): string {
  return `/* eslint-disable */
// @ts-nocheck
// Stub page — not yet extracted from clone.
// Satisfies TypeScript until the full clone-to-theme extraction covers this page type.

export function ${exportName}(props: Record<string, unknown>) {
  void props;
  return <main className="page-stub">{/* ${exportName} — stub */}</main>;
}
`;
}

/**
 * Scan a site's app directory to find all theme page component imports.
 * Returns a list of exported names needed from the theme's pages barrel.
 */
function findRequiredThemePageExports(siteDir: string, themeName: string): string[] {
  const appDir = path.join(siteDir, "app");
  if (!fs.existsSync(appDir)) return [];

  const needed: string[] = [];
  const importPattern = new RegExp(
    `import\\s+\\{([^}]+)\\}\\s+from\\s+['"]@platform/themes/${themeName}/pages['"]`,
    "g"
  );

  function scanDir(dir: string) {
    for (const entry of fs.readdirSync(dir)) {
      const fullPath = path.join(dir, entry);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        scanDir(fullPath);
      } else if (entry.endsWith(".tsx") || entry.endsWith(".ts")) {
        const content = fs.readFileSync(fullPath, "utf-8");
        let m: RegExpExecArray | null;
        while ((m = importPattern.exec(content)) !== null) {
          for (const name of m[1]
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean)) {
            if (!needed.includes(name)) needed.push(name);
          }
        }
      }
    }
  }

  scanDir(appDir);
  return needed;
}

function generateHeaderComponent(themeName: string): string {
  return `import type React from "react";

export function ${toPascalCase(themeName)}Header(props: Record<string, unknown>) {
  return (
    <header className="site-header">
      {/* ${themeName} header — extracted from reference clone */}
      <nav className="nav container">
        <a href="/" className="nav-logo">{String(props.siteName ?? "")}</a>
      </nav>
    </header>
  );
}
`;
}

function generateFooterComponent(themeName: string): string {
  return `import type React from "react";

export function ${toPascalCase(themeName)}Footer(props: Record<string, unknown>) {
  return (
    <footer className="site-footer">
      <div className="container">
        <p>&copy; {new Date().getFullYear()} {String(props.siteName ?? "")}</p>
      </div>
    </footer>
  );
}
`;
}

function generatePageLayout(themeName: string, pageName: string): string {
  const pascal = toPascalCase(themeName);
  const pagePascal = toPascalCase(pageName);
  return `interface ${pagePascal}PageProps {
  [key: string]: unknown;
}

export function ${pascal}${pagePascal}Page(props: ${pagePascal}PageProps) {
  void props;
  return (
    <main className="page-${pageName}">
      {/* ${themeName} ${pageName} layout — extracted from reference clone */}
    </main>
  );
}
`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs();

  let cloneName: string;
  let brief: JobBrief | null = null;

  const passArg = args.pass ?? "translate";
  if (!["translate", "strip", "both"].includes(passArg)) {
    console.error("--pass must be 'translate', 'strip', or 'both'");
    process.exit(1);
  }

  if (args.brief) {
    const rawPath = path.resolve(args.brief);
    if (!fs.existsSync(rawPath)) {
      console.error(`Brief file not found: ${rawPath}`);
      process.exit(1);
    }
    const raw = JSON.parse(fs.readFileSync(rawPath, "utf-8")) as unknown;
    const result = JobBriefSchema.safeParse(raw);
    if (!result.success) {
      console.error("Invalid brief:", result.error.format());
      process.exit(1);
    }
    brief = result.data;
    cloneName = brief.theme.name ?? brief.id;
  } else if (args.clone) {
    cloneName = args.clone;
    const discovered = discoverBrief(cloneName);
    if (discovered) {
      brief = discovered;
    } else {
      console.log("[extract] No brief found — strip pass will use limited defaults");
    }
  } else {
    console.error(
      "Usage: extract-theme.ts --clone <name> [--pass translate|strip|both] | --brief <path>"
    );
    process.exit(1);
  }

  const cloneDir = path.resolve(`output/clones/${cloneName}`);
  const themeName = cloneName;
  const themeDir = path.resolve(`packages/themes/${themeName}`);

  // Read clone source domain from meta.json
  const metaPath = path.join(cloneDir, "meta.json");
  let sourceDomain: string | undefined;
  if (fs.existsSync(metaPath)) {
    try {
      const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8")) as { sourceRef?: string };
      if (meta.sourceRef) {
        sourceDomain = meta.sourceRef.replace(/\/$/, ""); // strip trailing slash
        console.log(`[extract] Source domain: ${sourceDomain}`);
      }
    } catch {
      console.log("[extract] Could not read meta.json — URL sanitisation will be limited");
    }
  }

  console.log(`\nExtract Theme Pipeline`);
  console.log(`  Clone: ${cloneDir}`);
  console.log(`  Theme: ${themeDir}`);
  console.log(`  Pass: ${passArg}\n`);

  // ── Translate pass ────────────────────────────────────────────────────────
  if (passArg === "translate" || passArg === "both") {
    console.log("[extract] === Translate Pass ===");
    console.log("[extract] TODO: Translate pass not yet implemented.");
    console.log("[extract] This pass will use AI to generate native Tailwind components");
    console.log("[extract] from clone HTML/CSS/screenshots as reference material.");
    console.log(
      "[extract] See: output/sessions/2026-04-13_translate-pipeline/ for implementation brief."
    );
    // Future: vision analysis → section extraction → AI translation → page assembly → theme scaffold
  }

  // ── Strip pass ─────────────────────────────────────────────────────────────

  if (passArg === "strip" || passArg === "both") {
    console.log("[extract] === Strip Pass ===");

    const pagesDir = path.join(themeDir, "pages");
    const componentDir = path.join(themeDir, "components");

    if (!fs.existsSync(pagesDir)) {
      console.error(
        `[extract] Strip pass requires theme pages at ${pagesDir}. Run --pass translate first.`
      );
      process.exit(1);
    }

    const strippingConfig = {
      businessName: brief?.business.name ?? "",
      phone: brief?.business.phone,
      email: brief?.business.email,
      address: brief?.business.address
        ? { city: brief.business.address.city, postcode: brief.business.address.postcode }
        : undefined,
      sourceDomain,
    };

    // Strip page layouts — only process clone-verbatim files (marked @ts-nocheck)
    // Typed stub pages use proper template props and should not be processed by the stripper
    for (const file of fs.readdirSync(pagesDir).filter((f) => f.endsWith(".tsx"))) {
      const filePath = path.join(pagesDir, file);
      const jsx = fs.readFileSync(filePath, "utf-8");
      if (!jsx.includes("@ts-nocheck")) {
        console.log(`[extract]   Skip ${file} (typed stub — skip)`);
        continue;
      }
      const stripped = stripContent(jsx, strippingConfig);
      fs.writeFileSync(filePath, stripped.tsx, "utf-8");
      console.log(`[extract]   Stripped ${file}: ${stripped.propCount} props replaced`);
    }

    // Strip header/footer components — only if clone-verbatim (marked @ts-nocheck)
    // Typed stubs are not processed by the stripper
    for (const file of ["header.tsx", "footer.tsx"]) {
      const filePath = path.join(componentDir, file);
      if (fs.existsSync(filePath)) {
        const jsx = fs.readFileSync(filePath, "utf-8");
        if (!jsx.includes("@ts-nocheck")) {
          console.log(`[extract]   Skip ${file} (typed stub — skip)`);
          continue;
        }
        const stripped = stripContent(jsx, strippingConfig);
        fs.writeFileSync(filePath, stripped.tsx, "utf-8");
        console.log(`[extract]   Stripped ${file}: ${stripped.propCount} props replaced`);
      }
    }

    console.log("[extract] Strip pass complete");
  }

  console.log("\nDone.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
