#!/usr/bin/env tsx
/**
 * Scaffold Client Site CLI
 *
 * Copies base-template, wires theme, generates content from brief data,
 * and verifies the dev server starts.
 *
 * Usage:
 *   npx tsx tools/scaffold-client-site.ts --theme corvus --trade events --brief output/briefs/abc123.json
 */

import * as fs from "fs";
import * as path from "path";
import * as child_process from "child_process";

import { JobBriefSchema, type JobBrief } from "./lib/pipeline-brief-types";

// ── Argument parsing ─────────────────────────────────────────────────────────

function parseArgs(): { theme?: string; trade?: string; brief?: string } {
  const args = process.argv.slice(2);
  const result: { theme?: string; trade?: string; brief?: string } = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--theme" && args[i + 1]) result.theme = args[++i];
    else if (args[i] === "--trade" && args[i + 1]) result.trade = args[++i];
    else if (args[i] === "--brief" && args[i + 1]) result.brief = args[++i];
  }
  return result;
}

// ── File utilities ───────────────────────────────────────────────────────────

function copyDirRecursive(src: string, dest: string, exclude: string[] = []): void {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (exclude.includes(entry.name)) continue;
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath, exclude);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function findFilesRecursive(dir: string, extensions: string[], exclude: string[] = []): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (exclude.includes(entry.name)) continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findFilesRecursive(fullPath, extensions, exclude));
    } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
      results.push(fullPath);
    }
  }
  return results;
}

function replaceInFile(filePath: string, replacements: Record<string, string>): void {
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, "utf-8");
  for (const [from, to] of Object.entries(replacements)) {
    content = content.split(from).join(to);
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

// ── Template generators ──────────────────────────────────────────────────────

function generateSiteConfig(brief: JobBrief, themeName: string): string {
  const b = brief.business;
  const slug = `${themeName}-${b.trade}`.replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-");
  const name = b.name;
  const phone = b.phone || "+44 1234 567890";
  const email = b.email || "info@example.com";
  const city = b.address?.city || "City";
  const postcode = b.address?.postcode || "AB1 2CD";
  const region = b.address?.region || "County";
  const services = brief.content.services.map((s) => {
    const sSlug = s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    return { title: s, slug: sSlug, description: `Professional ${s.toLowerCase()} services.` };
  });
  const locations = (brief.content.locations ?? [city]).map((l) => l);

  return `/**
 * Site configuration — auto-generated by scaffold-client-site pipeline
 */

import type { BaseSiteConfig } from '@platform/core-components/types/site-config';
import type { BusinessConfig, LocalBusinessSchemaOptions } from '@platform/core-components';

export interface NavItem {
  label: string;
  href: string;
  hasDropdown?: boolean;
}

export interface CTAConfig {
  primary: { label: string; href: string };
  phone: { show: boolean; label?: string };
}

export interface FooterConfig {
  showServices: boolean;
  showLocations: boolean;
  maxServices: number;
  maxLocations: number;
  copyright: string;
  builtBy?: { name: string; url: string };
}

export interface CredentialStat {
  value: string;
  label: string;
  description?: string;
}

export interface Certification {
  name: string;
  description: string;
  icon?: string;
}

export interface CredentialsConfig {
  yearEstablished: string;
  stats: CredentialStat[];
  certifications: Certification[];
  insurance?: { amount: string; type: string };
}

export interface ServiceAreaRegion {
  name: string;
  slug: string;
  towns: Array<{ name: string; slug: string }>;
}

export interface SiteConfig extends BaseSiteConfig {
  name: string;
  tagline: string;
  url: string;
  business: {
    name: string;
    legalName: string;
    type: 'LocalBusiness' | 'ProfessionalService' | 'HomeAndConstructionBusiness';
    phone: string;
    email: string;
    address: {
      street: string;
      city: string;
      region: string;
      postalCode: string;
      country: string;
    };
    hours: Record<string, string>;
    socialMedia: Record<string, string>;
    geo?: { latitude: number; longitude: number };
  };
  navigation: { main: NavItem[] };
  cta: CTAConfig;
  footer: FooterConfig;
  credentials: CredentialsConfig;
  serviceAreas: string[];
  serviceAreaRegions?: ServiceAreaRegion[];
  services: Array<{ title: string; slug: string; description: string }>;
  features: {
    analytics: boolean;
    consentBanner: boolean;
    contactForm: boolean;
    rateLimit: boolean;
    testimonials: boolean;
    blog: boolean;
  };
  schema: {
    businessConfig: BusinessConfig;
    businessType: LocalBusinessSchemaOptions['businessType'];
  };
  about?: {
    heroBadges?: string[];
    story?: string[];
    whyChooseUs?: string[];
    values?: Array<{ title: string; description: string }>;
  };
}

export const siteConfig: SiteConfig = {
  slug: ${JSON.stringify(slug)},
  domain: 'localhost',
  name: ${JSON.stringify(name)},
  tagline: ${JSON.stringify(b.tagline || "Professional Local Services")},
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',

  business: {
    name: ${JSON.stringify(name)},
    legalName: ${JSON.stringify(name + " Ltd")},
    type: 'LocalBusiness',
    phone: ${JSON.stringify(phone)},
    email: ${JSON.stringify(email)},
    address: {
      street: '123 Main Street',
      city: ${JSON.stringify(city)},
      region: ${JSON.stringify(region)},
      postalCode: ${JSON.stringify(postcode)},
      country: 'United Kingdom',
    },
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed',
    },
    socialMedia: {},
  },

  navigation: {
    main: [
      { label: 'Services', href: '/services' },
      { label: 'Locations', href: '/locations', hasDropdown: true },
      { label: 'About', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
  },

  cta: {
    primary: { label: 'Get Free Quote', href: '/contact' },
    phone: { show: true, label: 'Call Us' },
  },

  footer: {
    showServices: true,
    showLocations: true,
    maxServices: 10,
    maxLocations: 12,
    copyright: '${new Date().getFullYear()} ${name}. All rights reserved.',
    builtBy: {
      name: 'Digital Consulting Services',
      url: 'https://www.digitalconsultingservices.co.uk',
    },
  },

  credentials: {
    yearEstablished: '2020',
    stats: [
      { value: '5+', label: 'Years Experience', description: 'Serving local customers' },
      { value: '500+', label: 'Projects Completed', description: 'Satisfied clients' },
      { value: '100%', label: 'Satisfaction', description: 'Customer focused' },
    ],
    certifications: [
      { name: 'Certified Professional', description: 'Industry certification' },
      { name: 'Fully Insured', description: 'Comprehensive coverage' },
    ],
    insurance: { amount: '£5M', type: 'Public Liability' },
  },

  serviceAreas: ${JSON.stringify(locations)},

  services: ${JSON.stringify(services, null, 4)},

  features: {
    analytics: false,
    consentBanner: false,
    contactForm: true,
    rateLimit: true,
    testimonials: true,
    blog: false,
  },

  schema: {
    businessType: 'LocalBusiness',
    businessConfig: {
      name: ${JSON.stringify(name)},
      legalName: ${JSON.stringify(name + " Ltd")},
      description: ${JSON.stringify(`Professional ${b.trade} services in ${city}. Quality workmanship and excellent customer service.`)},
      slogan: ${JSON.stringify(b.tagline || "Your trusted local experts")},
      foundingDate: '2020',
      numberOfEmployees: '1-10',
      priceRange: '$$',
      email: ${JSON.stringify(email)},
      telephone: ${JSON.stringify(phone.replace(/\\s/g, ""))},
      address: {
        streetAddress: '123 Main Street',
        addressLocality: ${JSON.stringify(city)},
        addressRegion: ${JSON.stringify(region)},
        postalCode: ${JSON.stringify(postcode)},
        addressCountry: 'GB',
      },
      geo: {
        latitude: '51.5074',
        longitude: '-0.1278',
      },
      openingHours: [
        {
          dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
          opens: '09:00',
          closes: '17:00',
        },
      ],
      areaServed: ${JSON.stringify(locations)},
    },
  },
};
`;
}

function generateServiceMdx(service: string, trade: string): string {
  const slug = service
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const title = service;
  const description = `Professional ${service.toLowerCase()} services.`;

  return `---
title: "${title}"
slug: "${slug}"
description: "${description}"
keywords: ["${service.toLowerCase()}", "${trade}", "professional"]
featured: true
---

# ${title}

We provide professional ${service.toLowerCase()} services.
`;
}

function generateLocationMdx(location: string, trade: string): string {
  const slug = location
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  return `---
title: "${location}"
slug: "${slug}"
description: "Professional ${trade} services in ${location}."
keywords: ["${trade}", "${location}"]
---

# ${trade.charAt(0).toUpperCase() + trade.slice(1)} Services in ${location}

Serving ${location} and surrounding areas.
`;
}

function generateBlogPost(index: number, businessName: string): string {
  const date = new Date().toISOString().split("T")[0];
  return `---
title: "Welcome to ${businessName}"
date: "${date}"
description: "Introducing our services and what we can do for you."
author: "${businessName} Team"
---

# Welcome to ${businessName}

We're excited to share more about our services.
`;
}

// ── Dev server check ─────────────────────────────────────────────────────────

async function checkDevServerStarts(siteDir: string): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = child_process.spawn("npx", ["next", "dev", "--port", "3798"], {
      cwd: siteDir,
      env: { ...process.env },
      stdio: ["ignore", "pipe", "pipe"],
    });

    const timeout = setTimeout(() => {
      proc.kill();
      resolve(false);
    }, 60_000);

    function onData(data: Buffer) {
      const text = data.toString();
      if (/Ready in|Local:|localhost:\d+/.test(text)) {
        clearTimeout(timeout);
        proc.kill();
        resolve(true);
      }
    }

    proc.stdout?.on("data", onData);
    proc.stderr?.on("data", onData);
    proc.on("error", () => {
      clearTimeout(timeout);
      resolve(false);
    });
  });
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const cliArgs = parseArgs();

  let brief: JobBrief;
  let themeName: string;
  let tradeName: string;

  if (cliArgs.brief) {
    const rawPath = path.resolve(cliArgs.brief);
    if (!fs.existsSync(rawPath)) {
      console.error(`Brief file not found: ${rawPath}`);
      process.exit(1);
    }
    const raw = JSON.parse(fs.readFileSync(rawPath, "utf-8")) as unknown;
    const result = JobBriefSchema.safeParse(raw);
    if (!result.success) {
      console.error("Invalid brief:", result.error.format());
      process.exit(1);
    }
    brief = result.data;
    themeName = cliArgs.theme ?? brief.theme.name ?? "vega";
    tradeName = cliArgs.trade ?? brief.business.trade;
  } else if (cliArgs.theme && cliArgs.trade) {
    // Minimal brief from flags — not enough without a brief file
    console.error(
      "--brief is required for full scaffolding. Use --brief with optional --theme and --trade overrides."
    );
    process.exit(1);
  } else {
    console.error(
      "Usage: scaffold-client-site.ts --brief <path> [--theme <name>] [--trade <name>]"
    );
    process.exit(1);
  }

  const sitePath = path.resolve(`sites/_${themeName}-${tradeName}`);
  const baseTemplatePath = path.resolve("sites/base-template");

  console.log(`\nScaffold Client Site`);
  console.log(`  Theme: ${themeName}`);
  console.log(`  Trade: ${tradeName}`);
  console.log(`  Output: ${sitePath}\n`);

  // Step 1: Copy base-template
  console.log("[scaffold] Step 1: Copying base-template...");
  if (fs.existsSync(sitePath)) {
    console.warn(`[scaffold] WARNING: Site directory already exists: ${sitePath}`);
  }
  copyDirRecursive(baseTemplatePath, sitePath, ["node_modules", ".next", ".turbo", "dist"]);
  console.log("[scaffold] Copied base-template");

  // Step 2: Wire theme
  console.log("[scaffold] Step 2: Wiring theme...");
  const themeConfigPath = path.join(sitePath, "theme.config.ts");
  if (fs.existsSync(themeConfigPath)) {
    replaceInFile(themeConfigPath, {
      vega: themeName,
      "@platform/themes/vega": `@platform/themes/${themeName}`,
    });
  }

  // Step 3: Update layout.tsx for theme header/footer
  const layoutPath = path.join(sitePath, "app", "layout.tsx");
  if (fs.existsSync(layoutPath)) {
    const pascal = themeName.charAt(0).toUpperCase() + themeName.slice(1);
    replaceInFile(layoutPath, {
      "@platform/themes/vega": `@platform/themes/${themeName}`,
      VegaHeader: `${pascal}Header`,
      VegaFooter: `${pascal}Footer`,
      vegaRegistry: `${themeName}Registry`,
      'theme="vega"': `theme="${themeName}"`,
    });
  }

  // Step 3b: Replace vega references in all page files and tsconfig
  console.log("[scaffold] Step 3b: Replacing vega references in page files...");
  const pascal = themeName.charAt(0).toUpperCase() + themeName.slice(1);
  const filesToPatch = findFilesRecursive(
    sitePath,
    [".tsx", ".ts", ".json", ".css"],
    ["node_modules", ".next"]
  );
  for (const file of filesToPatch) {
    if (file === layoutPath || file === themeConfigPath) continue; // already handled
    const content = fs.readFileSync(file, "utf-8");
    if (
      content.includes("@platform/themes/vega") ||
      content.includes("@platform/themes/orion") ||
      content.includes("Vega")
    ) {
      replaceInFile(file, {
        "@platform/themes/vega/pages": `@platform/themes/${themeName}/pages`,
        "@platform/themes/vega/components": `@platform/themes/${themeName}/components`,
        "@platform/themes/vega": `@platform/themes/${themeName}`,
        "@platform/themes/orion": `@platform/themes/${themeName}`,
        "../../packages/themes/vega/": `../../packages/themes/${themeName}/`,
        "../../packages/themes/orion/": `../../packages/themes/${themeName}/`,
      });
      // Replace component names (VegaHomePage → CorvusHomePage, etc.)
      let updated = fs.readFileSync(file, "utf-8");
      updated = updated.replace(/Vega(\w+Page)/g, `${pascal}$1`);
      updated = updated.replace(/vegaRegistry/g, `${themeName}Registry`);
      fs.writeFileSync(file, updated, "utf-8");
    }
  }

  // Step 4: Generate site.config.ts
  console.log("[scaffold] Step 4: Generating site.config.ts...");
  fs.writeFileSync(
    path.join(sitePath, "site.config.ts"),
    generateSiteConfig(brief, themeName),
    "utf-8"
  );

  // Step 5: Generate MDX content
  console.log("[scaffold] Step 5: Generating MDX content...");

  // Services
  const servicesDir = path.join(sitePath, "content", "services");
  fs.mkdirSync(servicesDir, { recursive: true });
  for (const service of brief.content.services) {
    const slug = service
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    fs.writeFileSync(
      path.join(servicesDir, `${slug}.mdx`),
      generateServiceMdx(service, tradeName),
      "utf-8"
    );
  }
  console.log(`[scaffold]   Generated ${brief.content.services.length} service MDX files`);

  // Locations
  if (brief.content.locations?.length) {
    const locationsDir = path.join(sitePath, "content", "locations");
    fs.mkdirSync(locationsDir, { recursive: true });
    for (const location of brief.content.locations) {
      const slug = location
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      fs.writeFileSync(
        path.join(locationsDir, `${slug}.mdx`),
        generateLocationMdx(location, tradeName),
        "utf-8"
      );
    }
    console.log(`[scaffold]   Generated ${brief.content.locations.length} location MDX files`);
  }

  // Placeholder blog posts
  const blogDir = path.join(sitePath, "content", "blog");
  fs.mkdirSync(blogDir, { recursive: true });
  fs.writeFileSync(
    path.join(blogDir, "welcome.mdx"),
    generateBlogPost(1, brief.business.name),
    "utf-8"
  );

  // Step 6: Set pipelineTestSite flag in package.json
  console.log("[scaffold] Step 6: Marking as pipeline test site...");
  const pkgPath = path.join(sitePath, "package.json");
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as Record<string, unknown>;
    pkg.pipelineTestSite = true;
    pkg.name = `${themeName}-${tradeName}`;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf-8");
  }

  // Step 7: Run pnpm install
  console.log("[scaffold] Step 7: Running pnpm install...");
  child_process.execSync("pnpm install", { cwd: sitePath, stdio: "inherit" });

  // Step 8: Verify dev server starts
  console.log("[scaffold] Step 8: Verifying dev server starts (timeout 60s)...");
  const started = await checkDevServerStarts(sitePath);
  if (started) {
    console.log("[scaffold] Dev server: READY");
  } else {
    console.warn(
      "[scaffold] Dev server: did not start within 60s (may still work — check manually)"
    );
  }

  console.log(`\nDone. Site scaffolded at: ${sitePath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
