/**
 * sync-themes.ts
 *
 * Scans packages/themes/ for theme directories (any folder containing index.ts)
 * and syncs the three places that must stay in step:
 *
 *   1. packages/theme-system/src/types.ts   — THEME_NAMES array
 *   2. packages/themes/package.json          — subpath exports
 *   3. sites/showcase/lib/register-all-themes.ts — side-effect imports
 *
 * Safe to re-run any time. Idempotent — no changes written if everything is
 * already up to date.
 *
 * Usage:
 *   pnpm sync:themes
 *   tsx tools/sync-themes.ts [--dry-run]
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join, resolve } from "path";

const ROOT = resolve(__dirname, "..");
const THEMES_DIR = join(ROOT, "packages/themes");
const TYPES_FILE = join(ROOT, "packages/theme-system/src/types.ts");
const THEMES_PKG = join(ROOT, "packages/themes/package.json");
const REGISTER_FILE = join(ROOT, "sites/showcase/lib/register-all-themes.ts");

const DRY_RUN = process.argv.includes("--dry-run");

// ─── Discover themes ──────────────────────────────────────────────────────────

function discoverThemes(): string[] {
  return readdirSync(THEMES_DIR, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        existsSync(join(THEMES_DIR, d.name, "index.ts"))
    )
    .map((d) => d.name)
    .sort();
}

// ─── 1. Update THEME_NAMES in types.ts ───────────────────────────────────────

function syncTypesFile(themes: string[]): boolean {
  const src = readFileSync(TYPES_FILE, "utf8");
  const arrayLiteral = themes.map((t) => `"${t}"`).join(", ");
  const next = src.replace(
    /export const THEME_NAMES = \[.*?\] as const;/,
    `export const THEME_NAMES = [${arrayLiteral}] as const;`
  );
  if (next === src) return false;
  if (!DRY_RUN) writeFileSync(TYPES_FILE, next, "utf8");
  return true;
}

// ─── 2. Update exports in packages/themes/package.json ───────────────────────

function buildExports(themes: string[]): Record<string, string> {
  const exports: Record<string, string> = {};
  for (const name of themes) {
    exports[`./${name}`] = `./${name}/index.ts`;
    const manifestPath = join(THEMES_DIR, name, "manifest.ts");
    if (existsSync(manifestPath)) {
      exports[`./${name}/manifest`] = `./${name}/manifest.ts`;
    }
    const showcasePath = join(THEMES_DIR, name, "showcase-registry.tsx");
    if (existsSync(showcasePath)) {
      exports[`./${name}/showcase`] = `./${name}/showcase-registry.tsx`;
    }
    const componentsIndex = join(THEMES_DIR, name, "components/index.ts");
    if (existsSync(componentsIndex)) {
      exports[`./${name}/components`] = `./${name}/components/index.ts`;
    }
  }
  return exports;
}

function syncThemesPkg(themes: string[]): boolean {
  const pkg = JSON.parse(readFileSync(THEMES_PKG, "utf8"));
  const next = buildExports(themes);
  const current = JSON.stringify(pkg.exports);
  const updated = JSON.stringify(next);
  if (current === updated) return false;
  pkg.exports = next;
  if (!DRY_RUN)
    writeFileSync(THEMES_PKG, JSON.stringify(pkg, null, 2) + "\n", "utf8");
  return true;
}

// ─── 3. Update register-all-themes.ts ────────────────────────────────────────

function buildRegisterFile(themes: string[]): string {
  const imports = themes
    .map((t) => `import '@platform/themes/${t}';`)
    .join("\n");
  return (
    `// Must be imported before reading getRegisteredThemes()\n` +
    `// Guarantees theme packages execute registerTheme() regardless of tree-shaking\n` +
    `// AUTO-GENERATED by tools/sync-themes.ts — do not edit manually\n` +
    imports +
    "\n"
  );
}

function syncRegisterFile(themes: string[]): boolean {
  const current = readFileSync(REGISTER_FILE, "utf8");
  const next = buildRegisterFile(themes);
  if (current === next) return false;
  if (!DRY_RUN) writeFileSync(REGISTER_FILE, next, "utf8");
  return true;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const themes = discoverThemes();
  console.log(`Discovered themes: ${themes.join(", ")}`);
  if (DRY_RUN) console.log("(dry-run — no files will be written)");

  const results = [
    { file: "packages/theme-system/src/types.ts", changed: syncTypesFile(themes) },
    { file: "packages/themes/package.json",        changed: syncThemesPkg(themes) },
    { file: "sites/showcase/lib/register-all-themes.ts", changed: syncRegisterFile(themes) },
  ];

  let anyChanged = false;
  for (const { file, changed } of results) {
    const status = changed ? (DRY_RUN ? "would update" : "updated") : "up to date";
    console.log(`  ${status.padEnd(12)} ${file}`);
    if (changed) anyChanged = true;
  }

  if (!anyChanged) {
    console.log("\nAll files already in sync.");
  } else if (!DRY_RUN) {
    console.log("\nSync complete.");
  }
}

main();
