/**
 * Site configuration — auto-generated by scaffold-client-site pipeline
 */

export const siteConfig = {
  name: 'Digital Marketing Weekend',
  trade: 'digital-marketing-events',
  tagline: 'Two days of practical marketing sessions, workshops, and networking',
  phone: '',
  email: 'hello@colorcode.events',
  address: {
    city: 'Eastbourne',
    postcode: 'BN21 4BP',
    region: 'East Sussex',
  },
  website: '',
  tone: 'friendly',
} as const;

export type SiteConfig = typeof siteConfig;
