/**
 * Site configuration — auto-generated by scaffold-client-site pipeline
 */

import type { BaseSiteConfig } from '@platform/core-components/types/site-config';
import type { BusinessConfig, LocalBusinessSchemaOptions } from '@platform/core-components';

export interface NavItem {
  label: string;
  href: string;
  hasDropdown?: boolean;
}

export interface CTAConfig {
  primary: { label: string; href: string };
  phone: { show: boolean; label?: string };
}

export interface FooterConfig {
  showServices: boolean;
  showLocations: boolean;
  maxServices: number;
  maxLocations: number;
  copyright: string;
  builtBy?: { name: string; url: string };
}

export interface CredentialStat {
  value: string;
  label: string;
  description?: string;
}

export interface Certification {
  name: string;
  description: string;
  icon?: string;
}

export interface CredentialsConfig {
  yearEstablished: string;
  stats: CredentialStat[];
  certifications: Certification[];
  insurance?: { amount: string; type: string };
}

export interface ServiceAreaRegion {
  name: string;
  slug: string;
  towns: Array<{ name: string; slug: string }>;
}

export interface SiteConfig extends BaseSiteConfig {
  name: string;
  tagline: string;
  url: string;
  business: {
    name: string;
    legalName: string;
    type: 'LocalBusiness' | 'ProfessionalService' | 'HomeAndConstructionBusiness';
    phone: string;
    email: string;
    address: {
      street: string;
      city: string;
      region: string;
      postalCode: string;
      country: string;
    };
    hours: Record<string, string>;
    socialMedia: Record<string, string>;
    geo?: { latitude: number; longitude: number };
  };
  navigation: { main: NavItem[] };
  cta: CTAConfig;
  footer: FooterConfig;
  credentials: CredentialsConfig;
  serviceAreas: string[];
  serviceAreaRegions?: ServiceAreaRegion[];
  services: Array<{ title: string; slug: string; description: string }>;
  features: {
    analytics: boolean;
    consentBanner: boolean;
    contactForm: boolean;
    rateLimit: boolean;
    testimonials: boolean;
    blog: boolean;
  };
  schema: {
    businessConfig: BusinessConfig;
    businessType: LocalBusinessSchemaOptions['businessType'];
  };
  about?: {
    heroBadges?: string[];
    story?: string[];
    whyChooseUs?: string[];
    values?: Array<{ title: string; description: string }>;
  };
}

export const siteConfig: SiteConfig = {
  slug: 'corvus-digital-marketing-events',
  domain: 'localhost',
  name: 'Digital Marketing Weekend',
  tagline: 'Two days of practical marketing sessions, workshops, and networking',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',

  business: {
    name: 'Digital Marketing Weekend',
    legalName: 'Digital Marketing Weekend Ltd',
    type: 'LocalBusiness',
    phone: '+44 1234 567890',
    email: 'hello@colorcode.events',
    address: {
      street: '123 Main Street',
      city: 'Eastbourne',
      region: 'East Sussex',
      postalCode: 'BN21 4BP',
      country: 'United Kingdom',
    },
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed',
    },
    socialMedia: {},
  },

  navigation: {
    main: [
      { label: 'Services', href: '/services' },
      { label: 'Locations', href: '/locations', hasDropdown: true },
      { label: 'About', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
  },

  cta: {
    primary: { label: 'Get Free Quote', href: '/contact' },
    phone: { show: true, label: 'Call Us' },
  },

  footer: {
    showServices: true,
    showLocations: true,
    maxServices: 10,
    maxLocations: 12,
    copyright: '2026 Digital Marketing Weekend. All rights reserved.',
    builtBy: {
      name: 'Digital Consulting Services',
      url: 'https://www.digitalconsultingservices.co.uk',
    },
  },

  credentials: {
    yearEstablished: '2020',
    stats: [
      { value: '5+', label: 'Years Experience', description: 'Serving local customers' },
      { value: '500+', label: 'Projects Completed', description: 'Satisfied clients' },
      { value: '100%', label: 'Satisfaction', description: 'Customer focused' },
    ],
    certifications: [
      { name: 'Certified Professional', description: 'Industry certification' },
      { name: 'Fully Insured', description: 'Comprehensive coverage' },
    ],
    insurance: { amount: '£5M', type: 'Public Liability' },
  },

  serviceAreas: ['Eastbourne'],

  services: [
    {
      title: 'Conference Sessions',
      slug: 'conference-sessions',
      description: 'Professional conference sessions services.',
    },
    { title: 'Workshops', slug: 'workshops', description: 'Professional workshops services.' },
    {
      title: 'Networking Events',
      slug: 'networking-events',
      description: 'Professional networking events services.',
    },
    {
      title: 'Speaker Presentations',
      slug: 'speaker-presentations',
      description: 'Professional speaker presentations services.',
    },
    {
      title: 'Panel Discussions',
      slug: 'panel-discussions',
      description: 'Professional panel discussions services.',
    },
  ],

  features: {
    analytics: false,
    consentBanner: false,
    contactForm: true,
    rateLimit: true,
    testimonials: true,
    blog: false,
  },

  schema: {
    businessType: 'LocalBusiness',
    businessConfig: {
      name: 'Digital Marketing Weekend',
      legalName: 'Digital Marketing Weekend Ltd',
      description:
        'Professional digital-marketing-events services in Eastbourne. Quality workmanship and excellent customer service.',
      slogan: 'Two days of practical marketing sessions, workshops, and networking',
      foundingDate: '2020',
      numberOfEmployees: '1-10',
      priceRange: '$$',
      email: 'hello@colorcode.events',
      telephone: '+441234567890',
      address: {
        streetAddress: '123 Main Street',
        addressLocality: 'Eastbourne',
        addressRegion: 'East Sussex',
        postalCode: 'BN21 4BP',
        addressCountry: 'GB',
      },
      geo: {
        latitude: '51.5074',
        longitude: '-0.1278',
      },
      openingHours: [
        {
          dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
          opens: '09:00',
          closes: '17:00',
        },
      ],
      areaServed: ['Eastbourne'],
    },
  },
};
