/**
 * Corvus Theme
 * Auto-generated by extract-theme pipeline
 */

export * from "./components";
export * from "./pages";

export const corvusConfig = {
  name: "corvus" as const,
};

export const corvusRegistry = {
  theme: "corvus" as const,
};
