/**
 * Corvus Theme
 * Auto-generated by extract-theme pipeline
 */

export * from "./components";
export * from "./pages";

export const corvusConfig = {
  name: "corvus" as const,
};

export const corvusRegistry: import("@platform/theme-system").ComponentRegistry = {
  theme: "corvus",
  heroVariant: "image-overlay",
  headerVariant: "dark",
  cardVariant: "standard",
  sectionVariant: "dark-accent",
};
