/**
 * Corvus Theme
 * Auto-generated by extract-theme pipeline
 */

import type { ComponentRegistry, DeepPartialThemeConfig } from "@platform/theme-system";
import { registerTheme } from "@platform/theme-system";

export const corvusRegistry: ComponentRegistry = {
  theme: "corvus",
  heroVariant: "image-overlay",
  headerVariant: "dark",
  cardVariant: "standard",
  sectionVariant: "standard",
};

export const corvusDefaultConfig: DeepPartialThemeConfig = {
  componentRegistry: corvusRegistry,
};

registerTheme({
  name: "corvus",
  label: "Corvus",
  config: corvusDefaultConfig,
});
